// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: openmls/openmls.proto

package openmls

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenMLSService_UploadKeyPackage_FullMethodName   = "/openim.openmls.OpenMLSService/UploadKeyPackage"
	OpenMLSService_GetKeyPackages_FullMethodName     = "/openim.openmls.OpenMLSService/GetKeyPackages"
	OpenMLSService_GetKeyPackageCount_FullMethodName = "/openim.openmls.OpenMLSService/GetKeyPackageCount"
	OpenMLSService_RefreshKeyPackages_FullMethodName = "/openim.openmls.OpenMLSService/RefreshKeyPackages"
	OpenMLSService_SubmitCommit_FullMethodName       = "/openim.openmls.OpenMLSService/SubmitCommit"
	OpenMLSService_GetCommits_FullMethodName         = "/openim.openmls.OpenMLSService/GetCommits"
	OpenMLSService_SendWelcome_FullMethodName        = "/openim.openmls.OpenMLSService/SendWelcome"
	OpenMLSService_GetGroupState_FullMethodName      = "/openim.openmls.OpenMLSService/GetGroupState"
	OpenMLSService_DeleteGroup_FullMethodName        = "/openim.openmls.OpenMLSService/DeleteGroup"
	OpenMLSService_IssueCredential_FullMethodName    = "/openim.openmls.OpenMLSService/IssueCredential"
	OpenMLSService_VerifyCredential_FullMethodName   = "/openim.openmls.OpenMLSService/VerifyCredential"
	OpenMLSService_GetRootPublicKey_FullMethodName   = "/openim.openmls.OpenMLSService/GetRootPublicKey"
)

// OpenMLSServiceClient is the client API for OpenMLSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenMLSServiceClient interface {
	// KeyPackage management
	UploadKeyPackage(ctx context.Context, in *UploadKeyPackageReq, opts ...grpc.CallOption) (*UploadKeyPackageResp, error)
	GetKeyPackages(ctx context.Context, in *GetKeyPackagesReq, opts ...grpc.CallOption) (*GetKeyPackagesResp, error)
	GetKeyPackageCount(ctx context.Context, in *GetKeyPackageCountReq, opts ...grpc.CallOption) (*GetKeyPackageCountResp, error)
	RefreshKeyPackages(ctx context.Context, in *RefreshKeyPackagesReq, opts ...grpc.CallOption) (*RefreshKeyPackagesResp, error)
	// Group Commit management
	SubmitCommit(ctx context.Context, in *SubmitCommitReq, opts ...grpc.CallOption) (*SubmitCommitResp, error)
	GetCommits(ctx context.Context, in *GetCommitsReq, opts ...grpc.CallOption) (*GetCommitsResp, error)
	SendWelcome(ctx context.Context, in *SendWelcomeReq, opts ...grpc.CallOption) (*SendWelcomeResp, error)
	GetGroupState(ctx context.Context, in *GetGroupStateReq, opts ...grpc.CallOption) (*GetGroupStateResp, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupReq, opts ...grpc.CallOption) (*DeleteGroupResp, error)
	// Credential management
	IssueCredential(ctx context.Context, in *IssueCredentialReq, opts ...grpc.CallOption) (*IssueCredentialResp, error)
	VerifyCredential(ctx context.Context, in *VerifyCredentialReq, opts ...grpc.CallOption) (*VerifyCredentialResp, error)
	GetRootPublicKey(ctx context.Context, in *GetRootPublicKeyReq, opts ...grpc.CallOption) (*GetRootPublicKeyResp, error)
}

type openMLSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenMLSServiceClient(cc grpc.ClientConnInterface) OpenMLSServiceClient {
	return &openMLSServiceClient{cc}
}

func (c *openMLSServiceClient) UploadKeyPackage(ctx context.Context, in *UploadKeyPackageReq, opts ...grpc.CallOption) (*UploadKeyPackageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadKeyPackageResp)
	err := c.cc.Invoke(ctx, OpenMLSService_UploadKeyPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) GetKeyPackages(ctx context.Context, in *GetKeyPackagesReq, opts ...grpc.CallOption) (*GetKeyPackagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPackagesResp)
	err := c.cc.Invoke(ctx, OpenMLSService_GetKeyPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) GetKeyPackageCount(ctx context.Context, in *GetKeyPackageCountReq, opts ...grpc.CallOption) (*GetKeyPackageCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyPackageCountResp)
	err := c.cc.Invoke(ctx, OpenMLSService_GetKeyPackageCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) RefreshKeyPackages(ctx context.Context, in *RefreshKeyPackagesReq, opts ...grpc.CallOption) (*RefreshKeyPackagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshKeyPackagesResp)
	err := c.cc.Invoke(ctx, OpenMLSService_RefreshKeyPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) SubmitCommit(ctx context.Context, in *SubmitCommitReq, opts ...grpc.CallOption) (*SubmitCommitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitCommitResp)
	err := c.cc.Invoke(ctx, OpenMLSService_SubmitCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) GetCommits(ctx context.Context, in *GetCommitsReq, opts ...grpc.CallOption) (*GetCommitsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommitsResp)
	err := c.cc.Invoke(ctx, OpenMLSService_GetCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) SendWelcome(ctx context.Context, in *SendWelcomeReq, opts ...grpc.CallOption) (*SendWelcomeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendWelcomeResp)
	err := c.cc.Invoke(ctx, OpenMLSService_SendWelcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) GetGroupState(ctx context.Context, in *GetGroupStateReq, opts ...grpc.CallOption) (*GetGroupStateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupStateResp)
	err := c.cc.Invoke(ctx, OpenMLSService_GetGroupState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupReq, opts ...grpc.CallOption) (*DeleteGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGroupResp)
	err := c.cc.Invoke(ctx, OpenMLSService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) IssueCredential(ctx context.Context, in *IssueCredentialReq, opts ...grpc.CallOption) (*IssueCredentialResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCredentialResp)
	err := c.cc.Invoke(ctx, OpenMLSService_IssueCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) VerifyCredential(ctx context.Context, in *VerifyCredentialReq, opts ...grpc.CallOption) (*VerifyCredentialResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCredentialResp)
	err := c.cc.Invoke(ctx, OpenMLSService_VerifyCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openMLSServiceClient) GetRootPublicKey(ctx context.Context, in *GetRootPublicKeyReq, opts ...grpc.CallOption) (*GetRootPublicKeyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRootPublicKeyResp)
	err := c.cc.Invoke(ctx, OpenMLSService_GetRootPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenMLSServiceServer is the server API for OpenMLSService service.
// All implementations must embed UnimplementedOpenMLSServiceServer
// for forward compatibility.
type OpenMLSServiceServer interface {
	// KeyPackage management
	UploadKeyPackage(context.Context, *UploadKeyPackageReq) (*UploadKeyPackageResp, error)
	GetKeyPackages(context.Context, *GetKeyPackagesReq) (*GetKeyPackagesResp, error)
	GetKeyPackageCount(context.Context, *GetKeyPackageCountReq) (*GetKeyPackageCountResp, error)
	RefreshKeyPackages(context.Context, *RefreshKeyPackagesReq) (*RefreshKeyPackagesResp, error)
	// Group Commit management
	SubmitCommit(context.Context, *SubmitCommitReq) (*SubmitCommitResp, error)
	GetCommits(context.Context, *GetCommitsReq) (*GetCommitsResp, error)
	SendWelcome(context.Context, *SendWelcomeReq) (*SendWelcomeResp, error)
	GetGroupState(context.Context, *GetGroupStateReq) (*GetGroupStateResp, error)
	DeleteGroup(context.Context, *DeleteGroupReq) (*DeleteGroupResp, error)
	// Credential management
	IssueCredential(context.Context, *IssueCredentialReq) (*IssueCredentialResp, error)
	VerifyCredential(context.Context, *VerifyCredentialReq) (*VerifyCredentialResp, error)
	GetRootPublicKey(context.Context, *GetRootPublicKeyReq) (*GetRootPublicKeyResp, error)
	mustEmbedUnimplementedOpenMLSServiceServer()
}

// UnimplementedOpenMLSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenMLSServiceServer struct{}

func (UnimplementedOpenMLSServiceServer) UploadKeyPackage(context.Context, *UploadKeyPackageReq) (*UploadKeyPackageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadKeyPackage not implemented")
}
func (UnimplementedOpenMLSServiceServer) GetKeyPackages(context.Context, *GetKeyPackagesReq) (*GetKeyPackagesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyPackages not implemented")
}
func (UnimplementedOpenMLSServiceServer) GetKeyPackageCount(context.Context, *GetKeyPackageCountReq) (*GetKeyPackageCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyPackageCount not implemented")
}
func (UnimplementedOpenMLSServiceServer) RefreshKeyPackages(context.Context, *RefreshKeyPackagesReq) (*RefreshKeyPackagesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshKeyPackages not implemented")
}
func (UnimplementedOpenMLSServiceServer) SubmitCommit(context.Context, *SubmitCommitReq) (*SubmitCommitResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitCommit not implemented")
}
func (UnimplementedOpenMLSServiceServer) GetCommits(context.Context, *GetCommitsReq) (*GetCommitsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommits not implemented")
}
func (UnimplementedOpenMLSServiceServer) SendWelcome(context.Context, *SendWelcomeReq) (*SendWelcomeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendWelcome not implemented")
}
func (UnimplementedOpenMLSServiceServer) GetGroupState(context.Context, *GetGroupStateReq) (*GetGroupStateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupState not implemented")
}
func (UnimplementedOpenMLSServiceServer) DeleteGroup(context.Context, *DeleteGroupReq) (*DeleteGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedOpenMLSServiceServer) IssueCredential(context.Context, *IssueCredentialReq) (*IssueCredentialResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCredential not implemented")
}
func (UnimplementedOpenMLSServiceServer) VerifyCredential(context.Context, *VerifyCredentialReq) (*VerifyCredentialResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCredential not implemented")
}
func (UnimplementedOpenMLSServiceServer) GetRootPublicKey(context.Context, *GetRootPublicKeyReq) (*GetRootPublicKeyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRootPublicKey not implemented")
}
func (UnimplementedOpenMLSServiceServer) mustEmbedUnimplementedOpenMLSServiceServer() {}
func (UnimplementedOpenMLSServiceServer) testEmbeddedByValue()                        {}

// UnsafeOpenMLSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenMLSServiceServer will
// result in compilation errors.
type UnsafeOpenMLSServiceServer interface {
	mustEmbedUnimplementedOpenMLSServiceServer()
}

func RegisterOpenMLSServiceServer(s grpc.ServiceRegistrar, srv OpenMLSServiceServer) {
	// If the following call panics, it indicates UnimplementedOpenMLSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenMLSService_ServiceDesc, srv)
}

func _OpenMLSService_UploadKeyPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadKeyPackageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).UploadKeyPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_UploadKeyPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).UploadKeyPackage(ctx, req.(*UploadKeyPackageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_GetKeyPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPackagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).GetKeyPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_GetKeyPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).GetKeyPackages(ctx, req.(*GetKeyPackagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_GetKeyPackageCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyPackageCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).GetKeyPackageCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_GetKeyPackageCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).GetKeyPackageCount(ctx, req.(*GetKeyPackageCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_RefreshKeyPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshKeyPackagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).RefreshKeyPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_RefreshKeyPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).RefreshKeyPackages(ctx, req.(*RefreshKeyPackagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_SubmitCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitCommitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).SubmitCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_SubmitCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).SubmitCommit(ctx, req.(*SubmitCommitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_GetCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).GetCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_GetCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).GetCommits(ctx, req.(*GetCommitsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_SendWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendWelcomeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).SendWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_SendWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).SendWelcome(ctx, req.(*SendWelcomeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_GetGroupState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).GetGroupState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_GetGroupState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).GetGroupState(ctx, req.(*GetGroupStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).DeleteGroup(ctx, req.(*DeleteGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_IssueCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCredentialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).IssueCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_IssueCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).IssueCredential(ctx, req.(*IssueCredentialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_VerifyCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCredentialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).VerifyCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_VerifyCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).VerifyCredential(ctx, req.(*VerifyCredentialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OpenMLSService_GetRootPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootPublicKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenMLSServiceServer).GetRootPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OpenMLSService_GetRootPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenMLSServiceServer).GetRootPublicKey(ctx, req.(*GetRootPublicKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OpenMLSService_ServiceDesc is the grpc.ServiceDesc for OpenMLSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenMLSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.openmls.OpenMLSService",
	HandlerType: (*OpenMLSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadKeyPackage",
			Handler:    _OpenMLSService_UploadKeyPackage_Handler,
		},
		{
			MethodName: "GetKeyPackages",
			Handler:    _OpenMLSService_GetKeyPackages_Handler,
		},
		{
			MethodName: "GetKeyPackageCount",
			Handler:    _OpenMLSService_GetKeyPackageCount_Handler,
		},
		{
			MethodName: "RefreshKeyPackages",
			Handler:    _OpenMLSService_RefreshKeyPackages_Handler,
		},
		{
			MethodName: "SubmitCommit",
			Handler:    _OpenMLSService_SubmitCommit_Handler,
		},
		{
			MethodName: "GetCommits",
			Handler:    _OpenMLSService_GetCommits_Handler,
		},
		{
			MethodName: "SendWelcome",
			Handler:    _OpenMLSService_SendWelcome_Handler,
		},
		{
			MethodName: "GetGroupState",
			Handler:    _OpenMLSService_GetGroupState_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _OpenMLSService_DeleteGroup_Handler,
		},
		{
			MethodName: "IssueCredential",
			Handler:    _OpenMLSService_IssueCredential_Handler,
		},
		{
			MethodName: "VerifyCredential",
			Handler:    _OpenMLSService_VerifyCredential_Handler,
		},
		{
			MethodName: "GetRootPublicKey",
			Handler:    _OpenMLSService_GetRootPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "openmls/openmls.proto",
}
