// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: openmls/openmls.proto

package openmls

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadKeyPackageReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID       string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	Platform       string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform"`
	KeyPackage     string                 `protobuf:"bytes,4,opt,name=keyPackage,proto3" json:"keyPackage"`
	Ciphersuite    string                 `protobuf:"bytes,5,opt,name=ciphersuite,proto3" json:"ciphersuite"`
	CredentialType string                 `protobuf:"bytes,6,opt,name=credentialType,proto3" json:"credentialType"`
	ExpiresAt      int64                  `protobuf:"varint,7,opt,name=expiresAt,proto3" json:"expiresAt"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadKeyPackageReq) Reset() {
	*x = UploadKeyPackageReq{}
	mi := &file_openmls_openmls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadKeyPackageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadKeyPackageReq) ProtoMessage() {}

func (x *UploadKeyPackageReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadKeyPackageReq.ProtoReflect.Descriptor instead.
func (*UploadKeyPackageReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{0}
}

func (x *UploadKeyPackageReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UploadKeyPackageReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *UploadKeyPackageReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *UploadKeyPackageReq) GetKeyPackage() string {
	if x != nil {
		return x.KeyPackage
	}
	return ""
}

func (x *UploadKeyPackageReq) GetCiphersuite() string {
	if x != nil {
		return x.Ciphersuite
	}
	return ""
}

func (x *UploadKeyPackageReq) GetCredentialType() string {
	if x != nil {
		return x.CredentialType
	}
	return ""
}

func (x *UploadKeyPackageReq) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type UploadKeyPackageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KpID          string                 `protobuf:"bytes,1,opt,name=kpID,proto3" json:"kpID"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadKeyPackageResp) Reset() {
	*x = UploadKeyPackageResp{}
	mi := &file_openmls_openmls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadKeyPackageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadKeyPackageResp) ProtoMessage() {}

func (x *UploadKeyPackageResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadKeyPackageResp.ProtoReflect.Descriptor instead.
func (*UploadKeyPackageResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{1}
}

func (x *UploadKeyPackageResp) GetKpID() string {
	if x != nil {
		return x.KpID
	}
	return ""
}

func (x *UploadKeyPackageResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type KeyPackageItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KpID          string                 `protobuf:"bytes,1,opt,name=kpID,proto3" json:"kpID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform"`
	KeyPackage    string                 `protobuf:"bytes,4,opt,name=keyPackage,proto3" json:"keyPackage"`
	Consumed      bool                   `protobuf:"varint,5,opt,name=consumed,proto3" json:"consumed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPackageItem) Reset() {
	*x = KeyPackageItem{}
	mi := &file_openmls_openmls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPackageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPackageItem) ProtoMessage() {}

func (x *KeyPackageItem) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPackageItem.ProtoReflect.Descriptor instead.
func (*KeyPackageItem) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{2}
}

func (x *KeyPackageItem) GetKpID() string {
	if x != nil {
		return x.KpID
	}
	return ""
}

func (x *KeyPackageItem) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *KeyPackageItem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *KeyPackageItem) GetKeyPackage() string {
	if x != nil {
		return x.KeyPackage
	}
	return ""
}

func (x *KeyPackageItem) GetConsumed() bool {
	if x != nil {
		return x.Consumed
	}
	return false
}

type GetKeyPackagesReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserID          string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	ExcludeDeviceID string                 `protobuf:"bytes,2,opt,name=excludeDeviceID,proto3" json:"excludeDeviceID"`
	CountPerDevice  int32                  `protobuf:"varint,3,opt,name=countPerDevice,proto3" json:"countPerDevice"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetKeyPackagesReq) Reset() {
	*x = GetKeyPackagesReq{}
	mi := &file_openmls_openmls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPackagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPackagesReq) ProtoMessage() {}

func (x *GetKeyPackagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPackagesReq.ProtoReflect.Descriptor instead.
func (*GetKeyPackagesReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{3}
}

func (x *GetKeyPackagesReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetKeyPackagesReq) GetExcludeDeviceID() string {
	if x != nil {
		return x.ExcludeDeviceID
	}
	return ""
}

func (x *GetKeyPackagesReq) GetCountPerDevice() int32 {
	if x != nil {
		return x.CountPerDevice
	}
	return 0
}

type GetKeyPackagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	KeyPackages   []*KeyPackageItem      `protobuf:"bytes,2,rep,name=keyPackages,proto3" json:"keyPackages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPackagesResp) Reset() {
	*x = GetKeyPackagesResp{}
	mi := &file_openmls_openmls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPackagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPackagesResp) ProtoMessage() {}

func (x *GetKeyPackagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPackagesResp.ProtoReflect.Descriptor instead.
func (*GetKeyPackagesResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{4}
}

func (x *GetKeyPackagesResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetKeyPackagesResp) GetKeyPackages() []*KeyPackageItem {
	if x != nil {
		return x.KeyPackages
	}
	return nil
}

type DeviceCount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceID       string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	AvailableCount int32                  `protobuf:"varint,2,opt,name=availableCount,proto3" json:"availableCount"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceCount) Reset() {
	*x = DeviceCount{}
	mi := &file_openmls_openmls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCount) ProtoMessage() {}

func (x *DeviceCount) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCount.ProtoReflect.Descriptor instead.
func (*DeviceCount) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceCount) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceCount) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

type GetKeyPackageCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyPackageCountReq) Reset() {
	*x = GetKeyPackageCountReq{}
	mi := &file_openmls_openmls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPackageCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPackageCountReq) ProtoMessage() {}

func (x *GetKeyPackageCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPackageCountReq.ProtoReflect.Descriptor instead.
func (*GetKeyPackageCountReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{6}
}

func (x *GetKeyPackageCountReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetKeyPackageCountResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Devices        []*DeviceCount         `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices"`
	TotalAvailable int32                  `protobuf:"varint,3,opt,name=totalAvailable,proto3" json:"totalAvailable"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetKeyPackageCountResp) Reset() {
	*x = GetKeyPackageCountResp{}
	mi := &file_openmls_openmls_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyPackageCountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyPackageCountResp) ProtoMessage() {}

func (x *GetKeyPackageCountResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyPackageCountResp.ProtoReflect.Descriptor instead.
func (*GetKeyPackageCountResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{7}
}

func (x *GetKeyPackageCountResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetKeyPackageCountResp) GetDevices() []*DeviceCount {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetKeyPackageCountResp) GetTotalAvailable() int32 {
	if x != nil {
		return x.TotalAvailable
	}
	return 0
}

type RefreshKeyPackagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	KeyPackages   []string               `protobuf:"bytes,3,rep,name=keyPackages,proto3" json:"keyPackages"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshKeyPackagesReq) Reset() {
	*x = RefreshKeyPackagesReq{}
	mi := &file_openmls_openmls_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshKeyPackagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshKeyPackagesReq) ProtoMessage() {}

func (x *RefreshKeyPackagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshKeyPackagesReq.ProtoReflect.Descriptor instead.
func (*RefreshKeyPackagesReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshKeyPackagesReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RefreshKeyPackagesReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RefreshKeyPackagesReq) GetKeyPackages() []string {
	if x != nil {
		return x.KeyPackages
	}
	return nil
}

type RefreshKeyPackagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadedCount int32                  `protobuf:"varint,1,opt,name=uploadedCount,proto3" json:"uploadedCount"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshKeyPackagesResp) Reset() {
	*x = RefreshKeyPackagesResp{}
	mi := &file_openmls_openmls_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshKeyPackagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshKeyPackagesResp) ProtoMessage() {}

func (x *RefreshKeyPackagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshKeyPackagesResp.ProtoReflect.Descriptor instead.
func (*RefreshKeyPackagesResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshKeyPackagesResp) GetUploadedCount() int32 {
	if x != nil {
		return x.UploadedCount
	}
	return 0
}

func (x *RefreshKeyPackagesResp) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type WelcomeMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RecipientUserID   string                 `protobuf:"bytes,1,opt,name=recipientUserID,proto3" json:"recipientUserID"`
	RecipientDeviceID string                 `protobuf:"bytes,2,opt,name=recipientDeviceID,proto3" json:"recipientDeviceID"`
	WelcomeMessage    string                 `protobuf:"bytes,3,opt,name=welcomeMessage,proto3" json:"welcomeMessage"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WelcomeMessage) Reset() {
	*x = WelcomeMessage{}
	mi := &file_openmls_openmls_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessage) ProtoMessage() {}

func (x *WelcomeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessage.ProtoReflect.Descriptor instead.
func (*WelcomeMessage) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{10}
}

func (x *WelcomeMessage) GetRecipientUserID() string {
	if x != nil {
		return x.RecipientUserID
	}
	return ""
}

func (x *WelcomeMessage) GetRecipientDeviceID() string {
	if x != nil {
		return x.RecipientDeviceID
	}
	return ""
}

func (x *WelcomeMessage) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

type SubmitCommitReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupID         string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	SenderUserID    string                 `protobuf:"bytes,2,opt,name=senderUserID,proto3" json:"senderUserID"`
	SenderDeviceID  string                 `protobuf:"bytes,3,opt,name=senderDeviceID,proto3" json:"senderDeviceID"`
	FromEpoch       uint64                 `protobuf:"varint,4,opt,name=fromEpoch,proto3" json:"fromEpoch"`
	CommitMessage   string                 `protobuf:"bytes,5,opt,name=commitMessage,proto3" json:"commitMessage"`
	WelcomeMessages []*WelcomeMessage      `protobuf:"bytes,6,rep,name=welcomeMessages,proto3" json:"welcomeMessages"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitCommitReq) Reset() {
	*x = SubmitCommitReq{}
	mi := &file_openmls_openmls_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommitReq) ProtoMessage() {}

func (x *SubmitCommitReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommitReq.ProtoReflect.Descriptor instead.
func (*SubmitCommitReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitCommitReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *SubmitCommitReq) GetSenderUserID() string {
	if x != nil {
		return x.SenderUserID
	}
	return ""
}

func (x *SubmitCommitReq) GetSenderDeviceID() string {
	if x != nil {
		return x.SenderDeviceID
	}
	return ""
}

func (x *SubmitCommitReq) GetFromEpoch() uint64 {
	if x != nil {
		return x.FromEpoch
	}
	return 0
}

func (x *SubmitCommitReq) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *SubmitCommitReq) GetWelcomeMessages() []*WelcomeMessage {
	if x != nil {
		return x.WelcomeMessages
	}
	return nil
}

type SubmitCommitResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewEpoch       uint64                 `protobuf:"varint,1,opt,name=newEpoch,proto3" json:"newEpoch"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequenceNumber,proto3" json:"sequenceNumber"`
	BroadcastCount int32                  `protobuf:"varint,3,opt,name=broadcastCount,proto3" json:"broadcastCount"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitCommitResp) Reset() {
	*x = SubmitCommitResp{}
	mi := &file_openmls_openmls_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCommitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCommitResp) ProtoMessage() {}

func (x *SubmitCommitResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCommitResp.ProtoReflect.Descriptor instead.
func (*SubmitCommitResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitCommitResp) GetNewEpoch() uint64 {
	if x != nil {
		return x.NewEpoch
	}
	return 0
}

func (x *SubmitCommitResp) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *SubmitCommitResp) GetBroadcastCount() int32 {
	if x != nil {
		return x.BroadcastCount
	}
	return 0
}

type GetCommitsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	SinceEpoch    uint64                 `protobuf:"varint,2,opt,name=sinceEpoch,proto3" json:"sinceEpoch"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitsReq) Reset() {
	*x = GetCommitsReq{}
	mi := &file_openmls_openmls_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitsReq) ProtoMessage() {}

func (x *GetCommitsReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitsReq.ProtoReflect.Descriptor instead.
func (*GetCommitsReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{13}
}

func (x *GetCommitsReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GetCommitsReq) GetSinceEpoch() uint64 {
	if x != nil {
		return x.SinceEpoch
	}
	return 0
}

func (x *GetCommitsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CommitRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Epoch          uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequenceNumber,proto3" json:"sequenceNumber"`
	CommitMessage  string                 `protobuf:"bytes,3,opt,name=commitMessage,proto3" json:"commitMessage"`
	SenderUserID   string                 `protobuf:"bytes,4,opt,name=senderUserID,proto3" json:"senderUserID"`
	CreatedAt      int64                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitRecord) Reset() {
	*x = CommitRecord{}
	mi := &file_openmls_openmls_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRecord) ProtoMessage() {}

func (x *CommitRecord) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRecord.ProtoReflect.Descriptor instead.
func (*CommitRecord) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{14}
}

func (x *CommitRecord) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *CommitRecord) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CommitRecord) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *CommitRecord) GetSenderUserID() string {
	if x != nil {
		return x.SenderUserID
	}
	return ""
}

func (x *CommitRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetCommitsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	Commits       []*CommitRecord        `protobuf:"bytes,2,rep,name=commits,proto3" json:"commits"`
	CurrentEpoch  uint64                 `protobuf:"varint,3,opt,name=currentEpoch,proto3" json:"currentEpoch"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitsResp) Reset() {
	*x = GetCommitsResp{}
	mi := &file_openmls_openmls_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitsResp) ProtoMessage() {}

func (x *GetCommitsResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitsResp.ProtoReflect.Descriptor instead.
func (*GetCommitsResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{15}
}

func (x *GetCommitsResp) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GetCommitsResp) GetCommits() []*CommitRecord {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *GetCommitsResp) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *GetCommitsResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SendWelcomeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	SenderUserID  string                 `protobuf:"bytes,2,opt,name=senderUserID,proto3" json:"senderUserID"`
	Recipients    []*WelcomeMessage      `protobuf:"bytes,3,rep,name=recipients,proto3" json:"recipients"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWelcomeReq) Reset() {
	*x = SendWelcomeReq{}
	mi := &file_openmls_openmls_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWelcomeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWelcomeReq) ProtoMessage() {}

func (x *SendWelcomeReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWelcomeReq.ProtoReflect.Descriptor instead.
func (*SendWelcomeReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{16}
}

func (x *SendWelcomeReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *SendWelcomeReq) GetSenderUserID() string {
	if x != nil {
		return x.SenderUserID
	}
	return ""
}

func (x *SendWelcomeReq) GetRecipients() []*WelcomeMessage {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type SendWelcomeResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeliveredCount int32                  `protobuf:"varint,1,opt,name=deliveredCount,proto3" json:"deliveredCount"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendWelcomeResp) Reset() {
	*x = SendWelcomeResp{}
	mi := &file_openmls_openmls_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWelcomeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWelcomeResp) ProtoMessage() {}

func (x *SendWelcomeResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWelcomeResp.ProtoReflect.Descriptor instead.
func (*SendWelcomeResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{17}
}

func (x *SendWelcomeResp) GetDeliveredCount() int32 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

type GetGroupStateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupStateReq) Reset() {
	*x = GetGroupStateReq{}
	mi := &file_openmls_openmls_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupStateReq) ProtoMessage() {}

func (x *GetGroupStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupStateReq.ProtoReflect.Descriptor instead.
func (*GetGroupStateReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{18}
}

func (x *GetGroupStateReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type GetGroupStateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	CurrentEpoch  uint64                 `protobuf:"varint,2,opt,name=currentEpoch,proto3" json:"currentEpoch"`
	MemberCount   int32                  `protobuf:"varint,3,opt,name=memberCount,proto3" json:"memberCount"`
	LastCommitAt  int64                  `protobuf:"varint,4,opt,name=lastCommitAt,proto3" json:"lastCommitAt"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupStateResp) Reset() {
	*x = GetGroupStateResp{}
	mi := &file_openmls_openmls_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupStateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupStateResp) ProtoMessage() {}

func (x *GetGroupStateResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupStateResp.ProtoReflect.Descriptor instead.
func (*GetGroupStateResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{19}
}

func (x *GetGroupStateResp) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GetGroupStateResp) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *GetGroupStateResp) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *GetGroupStateResp) GetLastCommitAt() int64 {
	if x != nil {
		return x.LastCommitAt
	}
	return 0
}

func (x *GetGroupStateResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DeleteGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupReq) Reset() {
	*x = DeleteGroupReq{}
	mi := &file_openmls_openmls_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupReq) ProtoMessage() {}

func (x *DeleteGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupReq.ProtoReflect.Descriptor instead.
func (*DeleteGroupReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteGroupReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type DeleteGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResp) Reset() {
	*x = DeleteGroupResp{}
	mi := &file_openmls_openmls_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResp) ProtoMessage() {}

func (x *DeleteGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResp.ProtoReflect.Descriptor instead.
func (*DeleteGroupResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{21}
}

type IssueCredentialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform"`
	LeafPublicKey string                 `protobuf:"bytes,4,opt,name=leafPublicKey,proto3" json:"leafPublicKey"`
	ClientVersion string                 `protobuf:"bytes,5,opt,name=clientVersion,proto3" json:"clientVersion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCredentialReq) Reset() {
	*x = IssueCredentialReq{}
	mi := &file_openmls_openmls_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCredentialReq) ProtoMessage() {}

func (x *IssueCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCredentialReq.ProtoReflect.Descriptor instead.
func (*IssueCredentialReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{22}
}

func (x *IssueCredentialReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *IssueCredentialReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *IssueCredentialReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *IssueCredentialReq) GetLeafPublicKey() string {
	if x != nil {
		return x.LeafPublicKey
	}
	return ""
}

func (x *IssueCredentialReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type IssueCredentialResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credential     string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential"`
	CredentialType string                 `protobuf:"bytes,2,opt,name=credentialType,proto3" json:"credentialType"`
	IssuedAt       int64                  `protobuf:"varint,3,opt,name=issuedAt,proto3" json:"issuedAt"`
	ExpiresAt      int64                  `protobuf:"varint,4,opt,name=expiresAt,proto3" json:"expiresAt"`
	Issuer         string                 `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IssueCredentialResp) Reset() {
	*x = IssueCredentialResp{}
	mi := &file_openmls_openmls_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCredentialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCredentialResp) ProtoMessage() {}

func (x *IssueCredentialResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCredentialResp.ProtoReflect.Descriptor instead.
func (*IssueCredentialResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{23}
}

func (x *IssueCredentialResp) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *IssueCredentialResp) GetCredentialType() string {
	if x != nil {
		return x.CredentialType
	}
	return ""
}

func (x *IssueCredentialResp) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *IssueCredentialResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *IssueCredentialResp) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type VerifyCredentialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    string                 `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialReq) Reset() {
	*x = VerifyCredentialReq{}
	mi := &file_openmls_openmls_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialReq) ProtoMessage() {}

func (x *VerifyCredentialReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialReq.ProtoReflect.Descriptor instead.
func (*VerifyCredentialReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{24}
}

func (x *VerifyCredentialReq) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

type VerifyCredentialResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,3,opt,name=deviceID,proto3" json:"deviceID"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expiresAt,proto3" json:"expiresAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialResp) Reset() {
	*x = VerifyCredentialResp{}
	mi := &file_openmls_openmls_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialResp) ProtoMessage() {}

func (x *VerifyCredentialResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialResp.ProtoReflect.Descriptor instead.
func (*VerifyCredentialResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{25}
}

func (x *VerifyCredentialResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyCredentialResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *VerifyCredentialResp) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *VerifyCredentialResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetRootPublicKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootPublicKeyReq) Reset() {
	*x = GetRootPublicKeyReq{}
	mi := &file_openmls_openmls_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootPublicKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootPublicKeyReq) ProtoMessage() {}

func (x *GetRootPublicKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootPublicKeyReq.ProtoReflect.Descriptor instead.
func (*GetRootPublicKeyReq) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{26}
}

type GetRootPublicKeyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey"`
	KeyID         string                 `protobuf:"bytes,2,opt,name=keyID,proto3" json:"keyID"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootPublicKeyResp) Reset() {
	*x = GetRootPublicKeyResp{}
	mi := &file_openmls_openmls_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootPublicKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootPublicKeyResp) ProtoMessage() {}

func (x *GetRootPublicKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_openmls_openmls_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootPublicKeyResp.ProtoReflect.Descriptor instead.
func (*GetRootPublicKeyResp) Descriptor() ([]byte, []int) {
	return file_openmls_openmls_proto_rawDescGZIP(), []int{27}
}

func (x *GetRootPublicKeyResp) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetRootPublicKeyResp) GetKeyID() string {
	if x != nil {
		return x.KeyID
	}
	return ""
}

func (x *GetRootPublicKeyResp) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

var File_openmls_openmls_proto protoreflect.FileDescriptor

const file_openmls_openmls_proto_rawDesc = "" +
	"\n" +
	"\x15openmls/openmls.proto\x12\x0eopenim.openmls\"\xed\x01\n" +
	"\x13UploadKeyPackageReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"keyPackage\x18\x04 \x01(\tR\n" +
	"keyPackage\x12 \n" +
	"\vciphersuite\x18\x05 \x01(\tR\vciphersuite\x12&\n" +
	"\x0ecredentialType\x18\x06 \x01(\tR\x0ecredentialType\x12\x1c\n" +
	"\texpiresAt\x18\a \x01(\x03R\texpiresAt\"J\n" +
	"\x14UploadKeyPackageResp\x12\x12\n" +
	"\x04kpID\x18\x01 \x01(\tR\x04kpID\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x98\x01\n" +
	"\x0eKeyPackageItem\x12\x12\n" +
	"\x04kpID\x18\x01 \x01(\tR\x04kpID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1e\n" +
	"\n" +
	"keyPackage\x18\x04 \x01(\tR\n" +
	"keyPackage\x12\x1a\n" +
	"\bconsumed\x18\x05 \x01(\bR\bconsumed\"}\n" +
	"\x11GetKeyPackagesReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12(\n" +
	"\x0fexcludeDeviceID\x18\x02 \x01(\tR\x0fexcludeDeviceID\x12&\n" +
	"\x0ecountPerDevice\x18\x03 \x01(\x05R\x0ecountPerDevice\"n\n" +
	"\x12GetKeyPackagesResp\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12@\n" +
	"\vkeyPackages\x18\x02 \x03(\v2\x1e.openim.openmls.KeyPackageItemR\vkeyPackages\"Q\n" +
	"\vDeviceCount\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12&\n" +
	"\x0eavailableCount\x18\x02 \x01(\x05R\x0eavailableCount\"/\n" +
	"\x15GetKeyPackageCountReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"\x8f\x01\n" +
	"\x16GetKeyPackageCountResp\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x125\n" +
	"\adevices\x18\x02 \x03(\v2\x1b.openim.openmls.DeviceCountR\adevices\x12&\n" +
	"\x0etotalAvailable\x18\x03 \x01(\x05R\x0etotalAvailable\"m\n" +
	"\x15RefreshKeyPackagesReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12 \n" +
	"\vkeyPackages\x18\x03 \x03(\tR\vkeyPackages\"^\n" +
	"\x16RefreshKeyPackagesResp\x12$\n" +
	"\ruploadedCount\x18\x01 \x01(\x05R\ruploadedCount\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x90\x01\n" +
	"\x0eWelcomeMessage\x12(\n" +
	"\x0frecipientUserID\x18\x01 \x01(\tR\x0frecipientUserID\x12,\n" +
	"\x11recipientDeviceID\x18\x02 \x01(\tR\x11recipientDeviceID\x12&\n" +
	"\x0ewelcomeMessage\x18\x03 \x01(\tR\x0ewelcomeMessage\"\x85\x02\n" +
	"\x0fSubmitCommitReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12\"\n" +
	"\fsenderUserID\x18\x02 \x01(\tR\fsenderUserID\x12&\n" +
	"\x0esenderDeviceID\x18\x03 \x01(\tR\x0esenderDeviceID\x12\x1c\n" +
	"\tfromEpoch\x18\x04 \x01(\x04R\tfromEpoch\x12$\n" +
	"\rcommitMessage\x18\x05 \x01(\tR\rcommitMessage\x12H\n" +
	"\x0fwelcomeMessages\x18\x06 \x03(\v2\x1e.openim.openmls.WelcomeMessageR\x0fwelcomeMessages\"~\n" +
	"\x10SubmitCommitResp\x12\x1a\n" +
	"\bnewEpoch\x18\x01 \x01(\x04R\bnewEpoch\x12&\n" +
	"\x0esequenceNumber\x18\x02 \x01(\x03R\x0esequenceNumber\x12&\n" +
	"\x0ebroadcastCount\x18\x03 \x01(\x05R\x0ebroadcastCount\"_\n" +
	"\rGetCommitsReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12\x1e\n" +
	"\n" +
	"sinceEpoch\x18\x02 \x01(\x04R\n" +
	"sinceEpoch\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xb4\x01\n" +
	"\fCommitRecord\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12&\n" +
	"\x0esequenceNumber\x18\x02 \x01(\x03R\x0esequenceNumber\x12$\n" +
	"\rcommitMessage\x18\x03 \x01(\tR\rcommitMessage\x12\"\n" +
	"\fsenderUserID\x18\x04 \x01(\tR\fsenderUserID\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x03R\tcreatedAt\"\xa0\x01\n" +
	"\x0eGetCommitsResp\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x126\n" +
	"\acommits\x18\x02 \x03(\v2\x1c.openim.openmls.CommitRecordR\acommits\x12\"\n" +
	"\fcurrentEpoch\x18\x03 \x01(\x04R\fcurrentEpoch\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"\x8e\x01\n" +
	"\x0eSendWelcomeReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12\"\n" +
	"\fsenderUserID\x18\x02 \x01(\tR\fsenderUserID\x12>\n" +
	"\n" +
	"recipients\x18\x03 \x03(\v2\x1e.openim.openmls.WelcomeMessageR\n" +
	"recipients\"9\n" +
	"\x0fSendWelcomeResp\x12&\n" +
	"\x0edeliveredCount\x18\x01 \x01(\x05R\x0edeliveredCount\",\n" +
	"\x10GetGroupStateReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\"\xb5\x01\n" +
	"\x11GetGroupStateResp\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12\"\n" +
	"\fcurrentEpoch\x18\x02 \x01(\x04R\fcurrentEpoch\x12 \n" +
	"\vmemberCount\x18\x03 \x01(\x05R\vmemberCount\x12\"\n" +
	"\flastCommitAt\x18\x04 \x01(\x03R\flastCommitAt\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\x03R\tcreatedAt\"*\n" +
	"\x0eDeleteGroupReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\"\x11\n" +
	"\x0fDeleteGroupResp\"\xb0\x01\n" +
	"\x12IssueCredentialReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12$\n" +
	"\rleafPublicKey\x18\x04 \x01(\tR\rleafPublicKey\x12$\n" +
	"\rclientVersion\x18\x05 \x01(\tR\rclientVersion\"\xaf\x01\n" +
	"\x13IssueCredentialResp\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\x12&\n" +
	"\x0ecredentialType\x18\x02 \x01(\tR\x0ecredentialType\x12\x1a\n" +
	"\bissuedAt\x18\x03 \x01(\x03R\bissuedAt\x12\x1c\n" +
	"\texpiresAt\x18\x04 \x01(\x03R\texpiresAt\x12\x16\n" +
	"\x06issuer\x18\x05 \x01(\tR\x06issuer\"5\n" +
	"\x13VerifyCredentialReq\x12\x1e\n" +
	"\n" +
	"credential\x18\x01 \x01(\tR\n" +
	"credential\"~\n" +
	"\x14VerifyCredentialResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x03 \x01(\tR\bdeviceID\x12\x1c\n" +
	"\texpiresAt\x18\x04 \x01(\x03R\texpiresAt\"\x15\n" +
	"\x13GetRootPublicKeyReq\"h\n" +
	"\x14GetRootPublicKeyResp\x12\x1c\n" +
	"\tpublicKey\x18\x01 \x01(\tR\tpublicKey\x12\x14\n" +
	"\x05keyID\x18\x02 \x01(\tR\x05keyID\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm2\xc2\b\n" +
	"\x0eOpenMLSService\x12]\n" +
	"\x10UploadKeyPackage\x12#.openim.openmls.UploadKeyPackageReq\x1a$.openim.openmls.UploadKeyPackageResp\x12W\n" +
	"\x0eGetKeyPackages\x12!.openim.openmls.GetKeyPackagesReq\x1a\".openim.openmls.GetKeyPackagesResp\x12c\n" +
	"\x12GetKeyPackageCount\x12%.openim.openmls.GetKeyPackageCountReq\x1a&.openim.openmls.GetKeyPackageCountResp\x12c\n" +
	"\x12RefreshKeyPackages\x12%.openim.openmls.RefreshKeyPackagesReq\x1a&.openim.openmls.RefreshKeyPackagesResp\x12Q\n" +
	"\fSubmitCommit\x12\x1f.openim.openmls.SubmitCommitReq\x1a .openim.openmls.SubmitCommitResp\x12K\n" +
	"\n" +
	"GetCommits\x12\x1d.openim.openmls.GetCommitsReq\x1a\x1e.openim.openmls.GetCommitsResp\x12N\n" +
	"\vSendWelcome\x12\x1e.openim.openmls.SendWelcomeReq\x1a\x1f.openim.openmls.SendWelcomeResp\x12T\n" +
	"\rGetGroupState\x12 .openim.openmls.GetGroupStateReq\x1a!.openim.openmls.GetGroupStateResp\x12N\n" +
	"\vDeleteGroup\x12\x1e.openim.openmls.DeleteGroupReq\x1a\x1f.openim.openmls.DeleteGroupResp\x12Z\n" +
	"\x0fIssueCredential\x12\".openim.openmls.IssueCredentialReq\x1a#.openim.openmls.IssueCredentialResp\x12]\n" +
	"\x10VerifyCredential\x12#.openim.openmls.VerifyCredentialReq\x1a$.openim.openmls.VerifyCredentialResp\x12]\n" +
	"\x10GetRootPublicKey\x12#.openim.openmls.GetRootPublicKeyReq\x1a$.openim.openmls.GetRootPublicKeyRespB'Z%github.com/openimsdk/protocol/openmlsb\x06proto3"

var (
	file_openmls_openmls_proto_rawDescOnce sync.Once
	file_openmls_openmls_proto_rawDescData []byte
)

func file_openmls_openmls_proto_rawDescGZIP() []byte {
	file_openmls_openmls_proto_rawDescOnce.Do(func() {
		file_openmls_openmls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openmls_openmls_proto_rawDesc), len(file_openmls_openmls_proto_rawDesc)))
	})
	return file_openmls_openmls_proto_rawDescData
}

var file_openmls_openmls_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_openmls_openmls_proto_goTypes = []any{
	(*UploadKeyPackageReq)(nil),    // 0: openim.openmls.UploadKeyPackageReq
	(*UploadKeyPackageResp)(nil),   // 1: openim.openmls.UploadKeyPackageResp
	(*KeyPackageItem)(nil),         // 2: openim.openmls.KeyPackageItem
	(*GetKeyPackagesReq)(nil),      // 3: openim.openmls.GetKeyPackagesReq
	(*GetKeyPackagesResp)(nil),     // 4: openim.openmls.GetKeyPackagesResp
	(*DeviceCount)(nil),            // 5: openim.openmls.DeviceCount
	(*GetKeyPackageCountReq)(nil),  // 6: openim.openmls.GetKeyPackageCountReq
	(*GetKeyPackageCountResp)(nil), // 7: openim.openmls.GetKeyPackageCountResp
	(*RefreshKeyPackagesReq)(nil),  // 8: openim.openmls.RefreshKeyPackagesReq
	(*RefreshKeyPackagesResp)(nil), // 9: openim.openmls.RefreshKeyPackagesResp
	(*WelcomeMessage)(nil),         // 10: openim.openmls.WelcomeMessage
	(*SubmitCommitReq)(nil),        // 11: openim.openmls.SubmitCommitReq
	(*SubmitCommitResp)(nil),       // 12: openim.openmls.SubmitCommitResp
	(*GetCommitsReq)(nil),          // 13: openim.openmls.GetCommitsReq
	(*CommitRecord)(nil),           // 14: openim.openmls.CommitRecord
	(*GetCommitsResp)(nil),         // 15: openim.openmls.GetCommitsResp
	(*SendWelcomeReq)(nil),         // 16: openim.openmls.SendWelcomeReq
	(*SendWelcomeResp)(nil),        // 17: openim.openmls.SendWelcomeResp
	(*GetGroupStateReq)(nil),       // 18: openim.openmls.GetGroupStateReq
	(*GetGroupStateResp)(nil),      // 19: openim.openmls.GetGroupStateResp
	(*DeleteGroupReq)(nil),         // 20: openim.openmls.DeleteGroupReq
	(*DeleteGroupResp)(nil),        // 21: openim.openmls.DeleteGroupResp
	(*IssueCredentialReq)(nil),     // 22: openim.openmls.IssueCredentialReq
	(*IssueCredentialResp)(nil),    // 23: openim.openmls.IssueCredentialResp
	(*VerifyCredentialReq)(nil),    // 24: openim.openmls.VerifyCredentialReq
	(*VerifyCredentialResp)(nil),   // 25: openim.openmls.VerifyCredentialResp
	(*GetRootPublicKeyReq)(nil),    // 26: openim.openmls.GetRootPublicKeyReq
	(*GetRootPublicKeyResp)(nil),   // 27: openim.openmls.GetRootPublicKeyResp
}
var file_openmls_openmls_proto_depIdxs = []int32{
	2,  // 0: openim.openmls.GetKeyPackagesResp.keyPackages:type_name -> openim.openmls.KeyPackageItem
	5,  // 1: openim.openmls.GetKeyPackageCountResp.devices:type_name -> openim.openmls.DeviceCount
	10, // 2: openim.openmls.SubmitCommitReq.welcomeMessages:type_name -> openim.openmls.WelcomeMessage
	14, // 3: openim.openmls.GetCommitsResp.commits:type_name -> openim.openmls.CommitRecord
	10, // 4: openim.openmls.SendWelcomeReq.recipients:type_name -> openim.openmls.WelcomeMessage
	0,  // 5: openim.openmls.OpenMLSService.UploadKeyPackage:input_type -> openim.openmls.UploadKeyPackageReq
	3,  // 6: openim.openmls.OpenMLSService.GetKeyPackages:input_type -> openim.openmls.GetKeyPackagesReq
	6,  // 7: openim.openmls.OpenMLSService.GetKeyPackageCount:input_type -> openim.openmls.GetKeyPackageCountReq
	8,  // 8: openim.openmls.OpenMLSService.RefreshKeyPackages:input_type -> openim.openmls.RefreshKeyPackagesReq
	11, // 9: openim.openmls.OpenMLSService.SubmitCommit:input_type -> openim.openmls.SubmitCommitReq
	13, // 10: openim.openmls.OpenMLSService.GetCommits:input_type -> openim.openmls.GetCommitsReq
	16, // 11: openim.openmls.OpenMLSService.SendWelcome:input_type -> openim.openmls.SendWelcomeReq
	18, // 12: openim.openmls.OpenMLSService.GetGroupState:input_type -> openim.openmls.GetGroupStateReq
	20, // 13: openim.openmls.OpenMLSService.DeleteGroup:input_type -> openim.openmls.DeleteGroupReq
	22, // 14: openim.openmls.OpenMLSService.IssueCredential:input_type -> openim.openmls.IssueCredentialReq
	24, // 15: openim.openmls.OpenMLSService.VerifyCredential:input_type -> openim.openmls.VerifyCredentialReq
	26, // 16: openim.openmls.OpenMLSService.GetRootPublicKey:input_type -> openim.openmls.GetRootPublicKeyReq
	1,  // 17: openim.openmls.OpenMLSService.UploadKeyPackage:output_type -> openim.openmls.UploadKeyPackageResp
	4,  // 18: openim.openmls.OpenMLSService.GetKeyPackages:output_type -> openim.openmls.GetKeyPackagesResp
	7,  // 19: openim.openmls.OpenMLSService.GetKeyPackageCount:output_type -> openim.openmls.GetKeyPackageCountResp
	9,  // 20: openim.openmls.OpenMLSService.RefreshKeyPackages:output_type -> openim.openmls.RefreshKeyPackagesResp
	12, // 21: openim.openmls.OpenMLSService.SubmitCommit:output_type -> openim.openmls.SubmitCommitResp
	15, // 22: openim.openmls.OpenMLSService.GetCommits:output_type -> openim.openmls.GetCommitsResp
	17, // 23: openim.openmls.OpenMLSService.SendWelcome:output_type -> openim.openmls.SendWelcomeResp
	19, // 24: openim.openmls.OpenMLSService.GetGroupState:output_type -> openim.openmls.GetGroupStateResp
	21, // 25: openim.openmls.OpenMLSService.DeleteGroup:output_type -> openim.openmls.DeleteGroupResp
	23, // 26: openim.openmls.OpenMLSService.IssueCredential:output_type -> openim.openmls.IssueCredentialResp
	25, // 27: openim.openmls.OpenMLSService.VerifyCredential:output_type -> openim.openmls.VerifyCredentialResp
	27, // 28: openim.openmls.OpenMLSService.GetRootPublicKey:output_type -> openim.openmls.GetRootPublicKeyResp
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_openmls_openmls_proto_init() }
func file_openmls_openmls_proto_init() {
	if File_openmls_openmls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openmls_openmls_proto_rawDesc), len(file_openmls_openmls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openmls_openmls_proto_goTypes,
		DependencyIndexes: file_openmls_openmls_proto_depIdxs,
		MessageInfos:      file_openmls_openmls_proto_msgTypes,
	}.Build()
	File_openmls_openmls_proto = out.File
	file_openmls_openmls_proto_goTypes = nil
	file_openmls_openmls_proto_depIdxs = nil
}
