// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: virgilsecurity/virgilsecurity.proto

package virgilsecurity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueVirgilJWTReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	TokenTtlSec   int32                  `protobuf:"varint,2,opt,name=tokenTtlSec,proto3" json:"tokenTtlSec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueVirgilJWTReq) Reset() {
	*x = IssueVirgilJWTReq{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueVirgilJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueVirgilJWTReq) ProtoMessage() {}

func (x *IssueVirgilJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueVirgilJWTReq.ProtoReflect.Descriptor instead.
func (*IssueVirgilJWTReq) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{0}
}

func (x *IssueVirgilJWTReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *IssueVirgilJWTReq) GetTokenTtlSec() int32 {
	if x != nil {
		return x.TokenTtlSec
	}
	return 0
}

type IssueVirgilJWTResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VirgilJwt     string                 `protobuf:"bytes,1,opt,name=virgilJwt,proto3" json:"virgilJwt"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expiresAt,proto3" json:"expiresAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueVirgilJWTResp) Reset() {
	*x = IssueVirgilJWTResp{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueVirgilJWTResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueVirgilJWTResp) ProtoMessage() {}

func (x *IssueVirgilJWTResp) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueVirgilJWTResp.ProtoReflect.Descriptor instead.
func (*IssueVirgilJWTResp) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{1}
}

func (x *IssueVirgilJWTResp) GetVirgilJwt() string {
	if x != nil {
		return x.VirgilJwt
	}
	return ""
}

func (x *IssueVirgilJWTResp) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *IssueVirgilJWTResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type DeviceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	CardID        string                 `protobuf:"bytes,2,opt,name=cardID,proto3" json:"cardID"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status"`
	ClientVersion string                 `protobuf:"bytes,5,opt,name=clientVersion,proto3" json:"clientVersion"`
	LastSeenAt    int64                  `protobuf:"varint,6,opt,name=lastSeenAt,proto3" json:"lastSeenAt"`
	RegisteredAt  int64                  `protobuf:"varint,7,opt,name=registeredAt,proto3" json:"registeredAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceItem) Reset() {
	*x = DeviceItem{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceItem) ProtoMessage() {}

func (x *DeviceItem) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceItem.ProtoReflect.Descriptor instead.
func (*DeviceItem) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceItem) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceItem) GetCardID() string {
	if x != nil {
		return x.CardID
	}
	return ""
}

func (x *DeviceItem) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceItem) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *DeviceItem) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *DeviceItem) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

type RegisterDeviceReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceID       string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	CardID         string                 `protobuf:"bytes,2,opt,name=cardID,proto3" json:"cardID"`
	Platform       string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform"`
	ClientVersion  string                 `protobuf:"bytes,4,opt,name=clientVersion,proto3" json:"clientVersion"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotencyKey,proto3" json:"idempotencyKey"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterDeviceReq) Reset() {
	*x = RegisterDeviceReq{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceReq) ProtoMessage() {}

func (x *RegisterDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceReq.ProtoReflect.Descriptor instead.
func (*RegisterDeviceReq) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterDeviceReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RegisterDeviceReq) GetCardID() string {
	if x != nil {
		return x.CardID
	}
	return ""
}

func (x *RegisterDeviceReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceReq) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *RegisterDeviceReq) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RegisterDeviceResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserID           string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID         string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	CardID           string                 `protobuf:"bytes,3,opt,name=cardID,proto3" json:"cardID"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status"`
	RegisteredAt     int64                  `protobuf:"varint,5,opt,name=registeredAt,proto3" json:"registeredAt"`
	IdempotentReplay bool                   `protobuf:"varint,6,opt,name=idempotentReplay,proto3" json:"idempotentReplay"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterDeviceResp) Reset() {
	*x = RegisterDeviceResp{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResp) ProtoMessage() {}

func (x *RegisterDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResp.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResp) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterDeviceResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RegisterDeviceResp) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RegisterDeviceResp) GetCardID() string {
	if x != nil {
		return x.CardID
	}
	return ""
}

func (x *RegisterDeviceResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterDeviceResp) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *RegisterDeviceResp) GetIdempotentReplay() bool {
	if x != nil {
		return x.IdempotentReplay
	}
	return false
}

type GetDevicesReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	IncludeRevoked bool                   `protobuf:"varint,2,opt,name=includeRevoked,proto3" json:"includeRevoked"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetDevicesReq) Reset() {
	*x = GetDevicesReq{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesReq) ProtoMessage() {}

func (x *GetDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesReq.ProtoReflect.Descriptor instead.
func (*GetDevicesReq) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{5}
}

func (x *GetDevicesReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetDevicesReq) GetIncludeRevoked() bool {
	if x != nil {
		return x.IncludeRevoked
	}
	return false
}

type GetDevicesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Devices       []*DeviceItem          `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResp) Reset() {
	*x = GetDevicesResp{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResp) ProtoMessage() {}

func (x *GetDevicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResp.ProtoReflect.Descriptor instead.
func (*GetDevicesResp) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{6}
}

func (x *GetDevicesResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetDevicesResp) GetDevices() []*DeviceItem {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *GetDevicesResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RevokeDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceReq) Reset() {
	*x = RevokeDeviceReq{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceReq) ProtoMessage() {}

func (x *RevokeDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceReq.ProtoReflect.Descriptor instead.
func (*RevokeDeviceReq) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeDeviceReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RevokeDeviceReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
	RevokedAt     int64                  `protobuf:"varint,3,opt,name=revokedAt,proto3" json:"revokedAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceResp) Reset() {
	*x = RevokeDeviceResp{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceResp) ProtoMessage() {}

func (x *RevokeDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceResp.ProtoReflect.Descriptor instead.
func (*RevokeDeviceResp) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeDeviceResp) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RevokeDeviceResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RevokeDeviceResp) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

type EnsureConversationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerUserID    string                 `protobuf:"bytes,1,opt,name=peerUserID,proto3" json:"peerUserID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureConversationReq) Reset() {
	*x = EnsureConversationReq{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureConversationReq) ProtoMessage() {}

func (x *EnsureConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureConversationReq.ProtoReflect.Descriptor instead.
func (*EnsureConversationReq) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{9}
}

func (x *EnsureConversationReq) GetPeerUserID() string {
	if x != nil {
		return x.PeerUserID
	}
	return ""
}

type EnsureConversationResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationID string                 `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID"`
	CreatedAt      int64                  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnsureConversationResp) Reset() {
	*x = EnsureConversationResp{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureConversationResp) ProtoMessage() {}

func (x *EnsureConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureConversationResp.ProtoReflect.Descriptor instead.
func (*EnsureConversationResp) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{10}
}

func (x *EnsureConversationResp) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *EnsureConversationResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DeviceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceID      string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceChange) Reset() {
	*x = DeviceChange{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceChange) ProtoMessage() {}

func (x *DeviceChange) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceChange.ProtoReflect.Descriptor instead.
func (*DeviceChange) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{11}
}

func (x *DeviceChange) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceChange) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SubscribeEventsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	SinceVersion  int64                  `protobuf:"varint,2,opt,name=sinceVersion,proto3" json:"sinceVersion"`
	TimeoutSec    int32                  `protobuf:"varint,3,opt,name=timeoutSec,proto3" json:"timeoutSec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsReq) Reset() {
	*x = SubscribeEventsReq{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsReq) ProtoMessage() {}

func (x *SubscribeEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsReq.ProtoReflect.Descriptor instead.
func (*SubscribeEventsReq) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeEventsReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SubscribeEventsReq) GetSinceVersion() int64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

func (x *SubscribeEventsReq) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version"`
	Changes       []*DeviceChange        `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{13}
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *EventEnvelope) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EventEnvelope) GetChanges() []*DeviceChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type SubscribeEventsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventEnvelope       `protobuf:"bytes,1,rep,name=events,proto3" json:"events"`
	LatestVersion int64                  `protobuf:"varint,2,opt,name=latestVersion,proto3" json:"latestVersion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsResp) Reset() {
	*x = SubscribeEventsResp{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsResp) ProtoMessage() {}

func (x *SubscribeEventsResp) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsResp.ProtoReflect.Descriptor instead.
func (*SubscribeEventsResp) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeEventsResp) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SubscribeEventsResp) GetLatestVersion() int64 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

type CreateUploadURLReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Size           int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size"`
	ContentType    string                 `protobuf:"bytes,2,opt,name=contentType,proto3" json:"contentType"`
	ConversationID string                 `protobuf:"bytes,3,opt,name=conversationID,proto3" json:"conversationID"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUploadURLReq) Reset() {
	*x = CreateUploadURLReq{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadURLReq) ProtoMessage() {}

func (x *CreateUploadURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadURLReq.ProtoReflect.Descriptor instead.
func (*CreateUploadURLReq) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{15}
}

func (x *CreateUploadURLReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CreateUploadURLReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadURLReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

type CreateUploadURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=uploadUrl,proto3" json:"uploadUrl"`
	DownloadUrl   string                 `protobuf:"bytes,2,opt,name=downloadUrl,proto3" json:"downloadUrl"`
	FileRefID     string                 `protobuf:"bytes,3,opt,name=fileRefID,proto3" json:"fileRefID"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expiresAt,proto3" json:"expiresAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadURLResp) Reset() {
	*x = CreateUploadURLResp{}
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadURLResp) ProtoMessage() {}

func (x *CreateUploadURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_virgilsecurity_virgilsecurity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadURLResp.ProtoReflect.Descriptor instead.
func (*CreateUploadURLResp) Descriptor() ([]byte, []int) {
	return file_virgilsecurity_virgilsecurity_proto_rawDescGZIP(), []int{16}
}

func (x *CreateUploadURLResp) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateUploadURLResp) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *CreateUploadURLResp) GetFileRefID() string {
	if x != nil {
		return x.FileRefID
	}
	return ""
}

func (x *CreateUploadURLResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_virgilsecurity_virgilsecurity_proto protoreflect.FileDescriptor

const file_virgilsecurity_virgilsecurity_proto_rawDesc = "" +
	"\n" +
	"#virgilsecurity/virgilsecurity.proto\x12\x15openim.virgilsecurity\"Q\n" +
	"\x11IssueVirgilJWTReq\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12 \n" +
	"\vtokenTtlSec\x18\x02 \x01(\x05R\vtokenTtlSec\"l\n" +
	"\x12IssueVirgilJWTResp\x12\x1c\n" +
	"\tvirgilJwt\x18\x01 \x01(\tR\tvirgilJwt\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x1c\n" +
	"\texpiresAt\x18\x03 \x01(\x03R\texpiresAt\"\xde\x01\n" +
	"\n" +
	"DeviceItem\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06cardID\x18\x02 \x01(\tR\x06cardID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12$\n" +
	"\rclientVersion\x18\x05 \x01(\tR\rclientVersion\x12\x1e\n" +
	"\n" +
	"lastSeenAt\x18\x06 \x01(\x03R\n" +
	"lastSeenAt\x12\"\n" +
	"\fregisteredAt\x18\a \x01(\x03R\fregisteredAt\"\xb1\x01\n" +
	"\x11RegisterDeviceReq\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06cardID\x18\x02 \x01(\tR\x06cardID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12$\n" +
	"\rclientVersion\x18\x04 \x01(\tR\rclientVersion\x12&\n" +
	"\x0eidempotencyKey\x18\x05 \x01(\tR\x0eidempotencyKey\"\xc8\x01\n" +
	"\x12RegisterDeviceResp\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06cardID\x18\x03 \x01(\tR\x06cardID\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\"\n" +
	"\fregisteredAt\x18\x05 \x01(\x03R\fregisteredAt\x12*\n" +
	"\x10idempotentReplay\x18\x06 \x01(\bR\x10idempotentReplay\"O\n" +
	"\rGetDevicesReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12&\n" +
	"\x0eincludeRevoked\x18\x02 \x01(\bR\x0eincludeRevoked\"\x7f\n" +
	"\x0eGetDevicesResp\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12;\n" +
	"\adevices\x18\x02 \x03(\v2!.openim.virgilsecurity.DeviceItemR\adevices\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"E\n" +
	"\x0fRevokeDeviceReq\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"d\n" +
	"\x10RevokeDeviceResp\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\trevokedAt\x18\x03 \x01(\x03R\trevokedAt\"7\n" +
	"\x15EnsureConversationReq\x12\x1e\n" +
	"\n" +
	"peerUserID\x18\x01 \x01(\tR\n" +
	"peerUserID\"^\n" +
	"\x16EnsureConversationResp\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\x03R\tcreatedAt\"B\n" +
	"\fDeviceChange\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"p\n" +
	"\x12SubscribeEventsReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\"\n" +
	"\fsinceVersion\x18\x02 \x01(\x03R\fsinceVersion\x12\x1e\n" +
	"\n" +
	"timeoutSec\x18\x03 \x01(\x05R\n" +
	"timeoutSec\"\x94\x01\n" +
	"\rEventEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12=\n" +
	"\achanges\x18\x04 \x03(\v2#.openim.virgilsecurity.DeviceChangeR\achanges\"y\n" +
	"\x13SubscribeEventsResp\x12<\n" +
	"\x06events\x18\x01 \x03(\v2$.openim.virgilsecurity.EventEnvelopeR\x06events\x12$\n" +
	"\rlatestVersion\x18\x02 \x01(\x03R\rlatestVersion\"r\n" +
	"\x12CreateUploadURLReq\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12 \n" +
	"\vcontentType\x18\x02 \x01(\tR\vcontentType\x12&\n" +
	"\x0econversationID\x18\x03 \x01(\tR\x0econversationID\"\x91\x01\n" +
	"\x13CreateUploadURLResp\x12\x1c\n" +
	"\tuploadUrl\x18\x01 \x01(\tR\tuploadUrl\x12 \n" +
	"\vdownloadUrl\x18\x02 \x01(\tR\vdownloadUrl\x12\x1c\n" +
	"\tfileRefID\x18\x03 \x01(\tR\tfileRefID\x12\x1c\n" +
	"\texpiresAt\x18\x04 \x01(\x03R\texpiresAt2\xe8\x05\n" +
	"\x15VirgilSecurityService\x12e\n" +
	"\x0eIssueVirgilJWT\x12(.openim.virgilsecurity.IssueVirgilJWTReq\x1a).openim.virgilsecurity.IssueVirgilJWTResp\x12e\n" +
	"\x0eRegisterDevice\x12(.openim.virgilsecurity.RegisterDeviceReq\x1a).openim.virgilsecurity.RegisterDeviceResp\x12Y\n" +
	"\n" +
	"GetDevices\x12$.openim.virgilsecurity.GetDevicesReq\x1a%.openim.virgilsecurity.GetDevicesResp\x12_\n" +
	"\fRevokeDevice\x12&.openim.virgilsecurity.RevokeDeviceReq\x1a'.openim.virgilsecurity.RevokeDeviceResp\x12q\n" +
	"\x12EnsureConversation\x12,.openim.virgilsecurity.EnsureConversationReq\x1a-.openim.virgilsecurity.EnsureConversationResp\x12h\n" +
	"\x0fSubscribeEvents\x12).openim.virgilsecurity.SubscribeEventsReq\x1a*.openim.virgilsecurity.SubscribeEventsResp\x12h\n" +
	"\x0fCreateUploadURL\x12).openim.virgilsecurity.CreateUploadURLReq\x1a*.openim.virgilsecurity.CreateUploadURLRespB.Z,github.com/openimsdk/protocol/virgilsecurityb\x06proto3"

var (
	file_virgilsecurity_virgilsecurity_proto_rawDescOnce sync.Once
	file_virgilsecurity_virgilsecurity_proto_rawDescData []byte
)

func file_virgilsecurity_virgilsecurity_proto_rawDescGZIP() []byte {
	file_virgilsecurity_virgilsecurity_proto_rawDescOnce.Do(func() {
		file_virgilsecurity_virgilsecurity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_virgilsecurity_virgilsecurity_proto_rawDesc), len(file_virgilsecurity_virgilsecurity_proto_rawDesc)))
	})
	return file_virgilsecurity_virgilsecurity_proto_rawDescData
}

var file_virgilsecurity_virgilsecurity_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_virgilsecurity_virgilsecurity_proto_goTypes = []any{
	(*IssueVirgilJWTReq)(nil),      // 0: openim.virgilsecurity.IssueVirgilJWTReq
	(*IssueVirgilJWTResp)(nil),     // 1: openim.virgilsecurity.IssueVirgilJWTResp
	(*DeviceItem)(nil),             // 2: openim.virgilsecurity.DeviceItem
	(*RegisterDeviceReq)(nil),      // 3: openim.virgilsecurity.RegisterDeviceReq
	(*RegisterDeviceResp)(nil),     // 4: openim.virgilsecurity.RegisterDeviceResp
	(*GetDevicesReq)(nil),          // 5: openim.virgilsecurity.GetDevicesReq
	(*GetDevicesResp)(nil),         // 6: openim.virgilsecurity.GetDevicesResp
	(*RevokeDeviceReq)(nil),        // 7: openim.virgilsecurity.RevokeDeviceReq
	(*RevokeDeviceResp)(nil),       // 8: openim.virgilsecurity.RevokeDeviceResp
	(*EnsureConversationReq)(nil),  // 9: openim.virgilsecurity.EnsureConversationReq
	(*EnsureConversationResp)(nil), // 10: openim.virgilsecurity.EnsureConversationResp
	(*DeviceChange)(nil),           // 11: openim.virgilsecurity.DeviceChange
	(*SubscribeEventsReq)(nil),     // 12: openim.virgilsecurity.SubscribeEventsReq
	(*EventEnvelope)(nil),          // 13: openim.virgilsecurity.EventEnvelope
	(*SubscribeEventsResp)(nil),    // 14: openim.virgilsecurity.SubscribeEventsResp
	(*CreateUploadURLReq)(nil),     // 15: openim.virgilsecurity.CreateUploadURLReq
	(*CreateUploadURLResp)(nil),    // 16: openim.virgilsecurity.CreateUploadURLResp
}
var file_virgilsecurity_virgilsecurity_proto_depIdxs = []int32{
	2,  // 0: openim.virgilsecurity.GetDevicesResp.devices:type_name -> openim.virgilsecurity.DeviceItem
	11, // 1: openim.virgilsecurity.EventEnvelope.changes:type_name -> openim.virgilsecurity.DeviceChange
	13, // 2: openim.virgilsecurity.SubscribeEventsResp.events:type_name -> openim.virgilsecurity.EventEnvelope
	0,  // 3: openim.virgilsecurity.VirgilSecurityService.IssueVirgilJWT:input_type -> openim.virgilsecurity.IssueVirgilJWTReq
	3,  // 4: openim.virgilsecurity.VirgilSecurityService.RegisterDevice:input_type -> openim.virgilsecurity.RegisterDeviceReq
	5,  // 5: openim.virgilsecurity.VirgilSecurityService.GetDevices:input_type -> openim.virgilsecurity.GetDevicesReq
	7,  // 6: openim.virgilsecurity.VirgilSecurityService.RevokeDevice:input_type -> openim.virgilsecurity.RevokeDeviceReq
	9,  // 7: openim.virgilsecurity.VirgilSecurityService.EnsureConversation:input_type -> openim.virgilsecurity.EnsureConversationReq
	12, // 8: openim.virgilsecurity.VirgilSecurityService.SubscribeEvents:input_type -> openim.virgilsecurity.SubscribeEventsReq
	15, // 9: openim.virgilsecurity.VirgilSecurityService.CreateUploadURL:input_type -> openim.virgilsecurity.CreateUploadURLReq
	1,  // 10: openim.virgilsecurity.VirgilSecurityService.IssueVirgilJWT:output_type -> openim.virgilsecurity.IssueVirgilJWTResp
	4,  // 11: openim.virgilsecurity.VirgilSecurityService.RegisterDevice:output_type -> openim.virgilsecurity.RegisterDeviceResp
	6,  // 12: openim.virgilsecurity.VirgilSecurityService.GetDevices:output_type -> openim.virgilsecurity.GetDevicesResp
	8,  // 13: openim.virgilsecurity.VirgilSecurityService.RevokeDevice:output_type -> openim.virgilsecurity.RevokeDeviceResp
	10, // 14: openim.virgilsecurity.VirgilSecurityService.EnsureConversation:output_type -> openim.virgilsecurity.EnsureConversationResp
	14, // 15: openim.virgilsecurity.VirgilSecurityService.SubscribeEvents:output_type -> openim.virgilsecurity.SubscribeEventsResp
	16, // 16: openim.virgilsecurity.VirgilSecurityService.CreateUploadURL:output_type -> openim.virgilsecurity.CreateUploadURLResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_virgilsecurity_virgilsecurity_proto_init() }
func file_virgilsecurity_virgilsecurity_proto_init() {
	if File_virgilsecurity_virgilsecurity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_virgilsecurity_virgilsecurity_proto_rawDesc), len(file_virgilsecurity_virgilsecurity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_virgilsecurity_virgilsecurity_proto_goTypes,
		DependencyIndexes: file_virgilsecurity_virgilsecurity_proto_depIdxs,
		MessageInfos:      file_virgilsecurity_virgilsecurity_proto_msgTypes,
	}.Build()
	File_virgilsecurity_virgilsecurity_proto = out.File
	file_virgilsecurity_virgilsecurity_proto_goTypes = nil
	file_virgilsecurity_virgilsecurity_proto_depIdxs = nil
}
