// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: virgilsecurity/virgilsecurity.proto

package virgilsecurity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VirgilSecurityService_IssueVirgilJWT_FullMethodName     = "/openim.virgilsecurity.VirgilSecurityService/IssueVirgilJWT"
	VirgilSecurityService_RegisterDevice_FullMethodName     = "/openim.virgilsecurity.VirgilSecurityService/RegisterDevice"
	VirgilSecurityService_GetDevices_FullMethodName         = "/openim.virgilsecurity.VirgilSecurityService/GetDevices"
	VirgilSecurityService_RevokeDevice_FullMethodName       = "/openim.virgilsecurity.VirgilSecurityService/RevokeDevice"
	VirgilSecurityService_EnsureConversation_FullMethodName = "/openim.virgilsecurity.VirgilSecurityService/EnsureConversation"
	VirgilSecurityService_SubscribeEvents_FullMethodName    = "/openim.virgilsecurity.VirgilSecurityService/SubscribeEvents"
	VirgilSecurityService_CreateUploadURL_FullMethodName    = "/openim.virgilsecurity.VirgilSecurityService/CreateUploadURL"
)

// VirgilSecurityServiceClient is the client API for VirgilSecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirgilSecurityServiceClient interface {
	// Virgil JWT
	IssueVirgilJWT(ctx context.Context, in *IssueVirgilJWTReq, opts ...grpc.CallOption) (*IssueVirgilJWTResp, error)
	// Device management
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
	GetDevices(ctx context.Context, in *GetDevicesReq, opts ...grpc.CallOption) (*GetDevicesResp, error)
	RevokeDevice(ctx context.Context, in *RevokeDeviceReq, opts ...grpc.CallOption) (*RevokeDeviceResp, error)
	// Conversation
	EnsureConversation(ctx context.Context, in *EnsureConversationReq, opts ...grpc.CallOption) (*EnsureConversationResp, error)
	// Event subscription (long poll semantics)
	SubscribeEvents(ctx context.Context, in *SubscribeEventsReq, opts ...grpc.CallOption) (*SubscribeEventsResp, error)
	// File upload helper
	CreateUploadURL(ctx context.Context, in *CreateUploadURLReq, opts ...grpc.CallOption) (*CreateUploadURLResp, error)
}

type virgilSecurityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVirgilSecurityServiceClient(cc grpc.ClientConnInterface) VirgilSecurityServiceClient {
	return &virgilSecurityServiceClient{cc}
}

func (c *virgilSecurityServiceClient) IssueVirgilJWT(ctx context.Context, in *IssueVirgilJWTReq, opts ...grpc.CallOption) (*IssueVirgilJWTResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueVirgilJWTResp)
	err := c.cc.Invoke(ctx, VirgilSecurityService_IssueVirgilJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virgilSecurityServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResp)
	err := c.cc.Invoke(ctx, VirgilSecurityService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virgilSecurityServiceClient) GetDevices(ctx context.Context, in *GetDevicesReq, opts ...grpc.CallOption) (*GetDevicesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevicesResp)
	err := c.cc.Invoke(ctx, VirgilSecurityService_GetDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virgilSecurityServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceReq, opts ...grpc.CallOption) (*RevokeDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDeviceResp)
	err := c.cc.Invoke(ctx, VirgilSecurityService_RevokeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virgilSecurityServiceClient) EnsureConversation(ctx context.Context, in *EnsureConversationReq, opts ...grpc.CallOption) (*EnsureConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureConversationResp)
	err := c.cc.Invoke(ctx, VirgilSecurityService_EnsureConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virgilSecurityServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsReq, opts ...grpc.CallOption) (*SubscribeEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeEventsResp)
	err := c.cc.Invoke(ctx, VirgilSecurityService_SubscribeEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virgilSecurityServiceClient) CreateUploadURL(ctx context.Context, in *CreateUploadURLReq, opts ...grpc.CallOption) (*CreateUploadURLResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUploadURLResp)
	err := c.cc.Invoke(ctx, VirgilSecurityService_CreateUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirgilSecurityServiceServer is the server API for VirgilSecurityService service.
// All implementations must embed UnimplementedVirgilSecurityServiceServer
// for forward compatibility.
type VirgilSecurityServiceServer interface {
	// Virgil JWT
	IssueVirgilJWT(context.Context, *IssueVirgilJWTReq) (*IssueVirgilJWTResp, error)
	// Device management
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error)
	GetDevices(context.Context, *GetDevicesReq) (*GetDevicesResp, error)
	RevokeDevice(context.Context, *RevokeDeviceReq) (*RevokeDeviceResp, error)
	// Conversation
	EnsureConversation(context.Context, *EnsureConversationReq) (*EnsureConversationResp, error)
	// Event subscription (long poll semantics)
	SubscribeEvents(context.Context, *SubscribeEventsReq) (*SubscribeEventsResp, error)
	// File upload helper
	CreateUploadURL(context.Context, *CreateUploadURLReq) (*CreateUploadURLResp, error)
	mustEmbedUnimplementedVirgilSecurityServiceServer()
}

// UnimplementedVirgilSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirgilSecurityServiceServer struct{}

func (UnimplementedVirgilSecurityServiceServer) IssueVirgilJWT(context.Context, *IssueVirgilJWTReq) (*IssueVirgilJWTResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueVirgilJWT not implemented")
}
func (UnimplementedVirgilSecurityServiceServer) RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedVirgilSecurityServiceServer) GetDevices(context.Context, *GetDevicesReq) (*GetDevicesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedVirgilSecurityServiceServer) RevokeDevice(context.Context, *RevokeDeviceReq) (*RevokeDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedVirgilSecurityServiceServer) EnsureConversation(context.Context, *EnsureConversationReq) (*EnsureConversationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureConversation not implemented")
}
func (UnimplementedVirgilSecurityServiceServer) SubscribeEvents(context.Context, *SubscribeEventsReq) (*SubscribeEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedVirgilSecurityServiceServer) CreateUploadURL(context.Context, *CreateUploadURLReq) (*CreateUploadURLResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUploadURL not implemented")
}
func (UnimplementedVirgilSecurityServiceServer) mustEmbedUnimplementedVirgilSecurityServiceServer() {}
func (UnimplementedVirgilSecurityServiceServer) testEmbeddedByValue()                               {}

// UnsafeVirgilSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirgilSecurityServiceServer will
// result in compilation errors.
type UnsafeVirgilSecurityServiceServer interface {
	mustEmbedUnimplementedVirgilSecurityServiceServer()
}

func RegisterVirgilSecurityServiceServer(s grpc.ServiceRegistrar, srv VirgilSecurityServiceServer) {
	// If the following call panics, it indicates UnimplementedVirgilSecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirgilSecurityService_ServiceDesc, srv)
}

func _VirgilSecurityService_IssueVirgilJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueVirgilJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirgilSecurityServiceServer).IssueVirgilJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirgilSecurityService_IssueVirgilJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirgilSecurityServiceServer).IssueVirgilJWT(ctx, req.(*IssueVirgilJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirgilSecurityService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirgilSecurityServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirgilSecurityService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirgilSecurityServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirgilSecurityService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirgilSecurityServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirgilSecurityService_GetDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirgilSecurityServiceServer).GetDevices(ctx, req.(*GetDevicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirgilSecurityService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirgilSecurityServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirgilSecurityService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirgilSecurityServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirgilSecurityService_EnsureConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirgilSecurityServiceServer).EnsureConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirgilSecurityService_EnsureConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirgilSecurityServiceServer).EnsureConversation(ctx, req.(*EnsureConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirgilSecurityService_SubscribeEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirgilSecurityServiceServer).SubscribeEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirgilSecurityService_SubscribeEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirgilSecurityServiceServer).SubscribeEvents(ctx, req.(*SubscribeEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirgilSecurityService_CreateUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirgilSecurityServiceServer).CreateUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirgilSecurityService_CreateUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirgilSecurityServiceServer).CreateUploadURL(ctx, req.(*CreateUploadURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VirgilSecurityService_ServiceDesc is the grpc.ServiceDesc for VirgilSecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirgilSecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.virgilsecurity.VirgilSecurityService",
	HandlerType: (*VirgilSecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueVirgilJWT",
			Handler:    _VirgilSecurityService_IssueVirgilJWT_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _VirgilSecurityService_RegisterDevice_Handler,
		},
		{
			MethodName: "GetDevices",
			Handler:    _VirgilSecurityService_GetDevices_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _VirgilSecurityService_RevokeDevice_Handler,
		},
		{
			MethodName: "EnsureConversation",
			Handler:    _VirgilSecurityService_EnsureConversation_Handler,
		},
		{
			MethodName: "SubscribeEvents",
			Handler:    _VirgilSecurityService_SubscribeEvents_Handler,
		},
		{
			MethodName: "CreateUploadURL",
			Handler:    _VirgilSecurityService_CreateUploadURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "virgilsecurity/virgilsecurity.proto",
}
