// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: captcha/captcha.proto

package captcha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCaptchaReq) Reset() {
	*x = GenerateCaptchaReq{}
	mi := &file_captcha_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCaptchaReq) ProtoMessage() {}

func (x *GenerateCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCaptchaReq.ProtoReflect.Descriptor instead.
func (*GenerateCaptchaReq) Descriptor() ([]byte, []int) {
	return file_captcha_captcha_proto_rawDescGZIP(), []int{0}
}

type GenerateCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaID     string                 `protobuf:"bytes,1,opt,name=captchaID,proto3" json:"captchaID"`
	MasterImage   string                 `protobuf:"bytes,2,opt,name=masterImage,proto3" json:"masterImage"`
	TileImage     string                 `protobuf:"bytes,3,opt,name=tileImage,proto3" json:"tileImage"`
	ExpireAt      int64                  `protobuf:"varint,4,opt,name=expireAt,proto3" json:"expireAt"`
	TileY         int32                  `protobuf:"varint,5,opt,name=tileY,proto3" json:"tileY"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCaptchaResp) Reset() {
	*x = GenerateCaptchaResp{}
	mi := &file_captcha_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCaptchaResp) ProtoMessage() {}

func (x *GenerateCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCaptchaResp.ProtoReflect.Descriptor instead.
func (*GenerateCaptchaResp) Descriptor() ([]byte, []int) {
	return file_captcha_captcha_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateCaptchaResp) GetCaptchaID() string {
	if x != nil {
		return x.CaptchaID
	}
	return ""
}

func (x *GenerateCaptchaResp) GetMasterImage() string {
	if x != nil {
		return x.MasterImage
	}
	return ""
}

func (x *GenerateCaptchaResp) GetTileImage() string {
	if x != nil {
		return x.TileImage
	}
	return ""
}

func (x *GenerateCaptchaResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *GenerateCaptchaResp) GetTileY() int32 {
	if x != nil {
		return x.TileY
	}
	return 0
}

type VerifyCaptchaReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaID     string                 `protobuf:"bytes,1,opt,name=captchaID,proto3" json:"captchaID"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaReq) Reset() {
	*x = VerifyCaptchaReq{}
	mi := &file_captcha_captcha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaReq) ProtoMessage() {}

func (x *VerifyCaptchaReq) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_captcha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaReq.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaReq) Descriptor() ([]byte, []int) {
	return file_captcha_captcha_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCaptchaReq) GetCaptchaID() string {
	if x != nil {
		return x.CaptchaID
	}
	return ""
}

func (x *VerifyCaptchaReq) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *VerifyCaptchaReq) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type VerifyCaptchaResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCaptchaResp) Reset() {
	*x = VerifyCaptchaResp{}
	mi := &file_captcha_captcha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCaptchaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCaptchaResp) ProtoMessage() {}

func (x *VerifyCaptchaResp) ProtoReflect() protoreflect.Message {
	mi := &file_captcha_captcha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCaptchaResp.ProtoReflect.Descriptor instead.
func (*VerifyCaptchaResp) Descriptor() ([]byte, []int) {
	return file_captcha_captcha_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCaptchaResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_captcha_captcha_proto protoreflect.FileDescriptor

const file_captcha_captcha_proto_rawDesc = "" +
	"\n" +
	"\x15captcha/captcha.proto\x12\x0eopenim.captcha\"\x14\n" +
	"\x12generateCaptchaReq\"\xa5\x01\n" +
	"\x13generateCaptchaResp\x12\x1c\n" +
	"\tcaptchaID\x18\x01 \x01(\tR\tcaptchaID\x12 \n" +
	"\vmasterImage\x18\x02 \x01(\tR\vmasterImage\x12\x1c\n" +
	"\ttileImage\x18\x03 \x01(\tR\ttileImage\x12\x1a\n" +
	"\bexpireAt\x18\x04 \x01(\x03R\bexpireAt\x12\x14\n" +
	"\x05tileY\x18\x05 \x01(\x05R\x05tileY\"L\n" +
	"\x10verifyCaptchaReq\x12\x1c\n" +
	"\tcaptchaID\x18\x01 \x01(\tR\tcaptchaID\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"-\n" +
	"\x11verifyCaptchaResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xbb\x01\n" +
	"\aCaptcha\x12Z\n" +
	"\x0fgenerateCaptcha\x12\".openim.captcha.generateCaptchaReq\x1a#.openim.captcha.generateCaptchaResp\x12T\n" +
	"\rverifyCaptcha\x12 .openim.captcha.verifyCaptchaReq\x1a!.openim.captcha.verifyCaptchaRespB'Z%github.com/openimsdk/protocol/captchab\x06proto3"

var (
	file_captcha_captcha_proto_rawDescOnce sync.Once
	file_captcha_captcha_proto_rawDescData []byte
)

func file_captcha_captcha_proto_rawDescGZIP() []byte {
	file_captcha_captcha_proto_rawDescOnce.Do(func() {
		file_captcha_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_captcha_captcha_proto_rawDesc), len(file_captcha_captcha_proto_rawDesc)))
	})
	return file_captcha_captcha_proto_rawDescData
}

var file_captcha_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_captcha_captcha_proto_goTypes = []any{
	(*GenerateCaptchaReq)(nil),  // 0: openim.captcha.generateCaptchaReq
	(*GenerateCaptchaResp)(nil), // 1: openim.captcha.generateCaptchaResp
	(*VerifyCaptchaReq)(nil),    // 2: openim.captcha.verifyCaptchaReq
	(*VerifyCaptchaResp)(nil),   // 3: openim.captcha.verifyCaptchaResp
}
var file_captcha_captcha_proto_depIdxs = []int32{
	0, // 0: openim.captcha.Captcha.generateCaptcha:input_type -> openim.captcha.generateCaptchaReq
	2, // 1: openim.captcha.Captcha.verifyCaptcha:input_type -> openim.captcha.verifyCaptchaReq
	1, // 2: openim.captcha.Captcha.generateCaptcha:output_type -> openim.captcha.generateCaptchaResp
	3, // 3: openim.captcha.Captcha.verifyCaptcha:output_type -> openim.captcha.verifyCaptchaResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_captcha_captcha_proto_init() }
func file_captcha_captcha_proto_init() {
	if File_captcha_captcha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_captcha_captcha_proto_rawDesc), len(file_captcha_captcha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_captcha_captcha_proto_goTypes,
		DependencyIndexes: file_captcha_captcha_proto_depIdxs,
		MessageInfos:      file_captcha_captcha_proto_msgTypes,
	}.Build()
	File_captcha_captcha_proto = out.File
	file_captcha_captcha_proto_goTypes = nil
	file_captcha_captcha_proto_depIdxs = nil
}
