// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: totp/totp.proto

package totp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSecretReq is called by a logged-in user to initiate TOTP binding.
type GetSecretReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer"`           // e.g. "SOK-IM"
	AccountName   string                 `protobuf:"bytes,3,opt,name=accountName,proto3" json:"accountName"` // e.g. phone number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretReq) Reset() {
	*x = GetSecretReq{}
	mi := &file_totp_totp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretReq) ProtoMessage() {}

func (x *GetSecretReq) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretReq.ProtoReflect.Descriptor instead.
func (*GetSecretReq) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecretReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetSecretReq) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *GetSecretReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type GetSecretResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret"`         // Base32-encoded shared secret
	OtpAuthUrl    string                 `protobuf:"bytes,2,opt,name=otpAuthUrl,proto3" json:"otpAuthUrl"` // otpauth://totp/... URI for QR code
	ExpireAt      int64                  `protobuf:"varint,3,opt,name=expireAt,proto3" json:"expireAt"`    // Unix seconds when the temporary secret expires (10 min)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResp) Reset() {
	*x = GetSecretResp{}
	mi := &file_totp_totp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResp) ProtoMessage() {}

func (x *GetSecretResp) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResp.ProtoReflect.Descriptor instead.
func (*GetSecretResp) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecretResp) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetSecretResp) GetOtpAuthUrl() string {
	if x != nil {
		return x.OtpAuthUrl
	}
	return ""
}

func (x *GetSecretResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// BindTotpReq is called after the user scans the QR code and inputs the first code.
type BindTotpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	TotpCode      string                 `protobuf:"bytes,2,opt,name=totpCode,proto3" json:"totpCode"` // 6-digit dynamic code from Authenticator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindTotpReq) Reset() {
	*x = BindTotpReq{}
	mi := &file_totp_totp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindTotpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTotpReq) ProtoMessage() {}

func (x *BindTotpReq) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTotpReq.ProtoReflect.Descriptor instead.
func (*BindTotpReq) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{2}
}

func (x *BindTotpReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *BindTotpReq) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

type BindTotpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecoveryCodes []string               `protobuf:"bytes,1,rep,name=recoveryCodes,proto3" json:"recoveryCodes"` // 8 one-time recovery codes, shown only once
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindTotpResp) Reset() {
	*x = BindTotpResp{}
	mi := &file_totp_totp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindTotpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindTotpResp) ProtoMessage() {}

func (x *BindTotpResp) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindTotpResp.ProtoReflect.Descriptor instead.
func (*BindTotpResp) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{3}
}

func (x *BindTotpResp) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

// VerifyTotpReq is the second step of login when TOTP is enabled.
type VerifyTotpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MfaToken      string                 `protobuf:"bytes,1,opt,name=mfaToken,proto3" json:"mfaToken"`  // temporary token from the first login step
	TotpCode      string                 `protobuf:"bytes,2,opt,name=totpCode,proto3" json:"totpCode"`  // 6-digit TOTP code or 8-char recovery code
	Platform      int32                  `protobuf:"varint,3,opt,name=platform,proto3" json:"platform"` // 1:iOS 2:Android 3:Windows 4:macOS 5:Web
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTotpReq) Reset() {
	*x = VerifyTotpReq{}
	mi := &file_totp_totp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTotpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTotpReq) ProtoMessage() {}

func (x *VerifyTotpReq) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTotpReq.ProtoReflect.Descriptor instead.
func (*VerifyTotpReq) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyTotpReq) GetMfaToken() string {
	if x != nil {
		return x.MfaToken
	}
	return ""
}

func (x *VerifyTotpReq) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

func (x *VerifyTotpReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

type VerifyTotpResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserID            string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	RecoveryCodesLow  bool                   `protobuf:"varint,2,opt,name=recoveryCodesLow,proto3" json:"recoveryCodesLow"` // true when remaining recovery codes < 3
	RecoveryCodesLeft int32                  `protobuf:"varint,3,opt,name=recoveryCodesLeft,proto3" json:"recoveryCodesLeft"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyTotpResp) Reset() {
	*x = VerifyTotpResp{}
	mi := &file_totp_totp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTotpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTotpResp) ProtoMessage() {}

func (x *VerifyTotpResp) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTotpResp.ProtoReflect.Descriptor instead.
func (*VerifyTotpResp) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyTotpResp) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *VerifyTotpResp) GetRecoveryCodesLow() bool {
	if x != nil {
		return x.RecoveryCodesLow
	}
	return false
}

func (x *VerifyTotpResp) GetRecoveryCodesLeft() int32 {
	if x != nil {
		return x.RecoveryCodesLeft
	}
	return 0
}

// GetStatusReq queries the TOTP binding status for a user.
type GetStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusReq) Reset() {
	*x = GetStatusReq{}
	mi := &file_totp_totp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusReq) ProtoMessage() {}

func (x *GetStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusReq.ProtoReflect.Descriptor instead.
func (*GetStatusReq) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetStatusResp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Enabled                bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled"`
	BoundAt                int64                  `protobuf:"varint,2,opt,name=boundAt,proto3" json:"boundAt"` // Unix seconds; 0 if not bound
	RecoveryCodesRemaining int32                  `protobuf:"varint,3,opt,name=recoveryCodesRemaining,proto3" json:"recoveryCodesRemaining"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetStatusResp) Reset() {
	*x = GetStatusResp{}
	mi := &file_totp_totp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResp) ProtoMessage() {}

func (x *GetStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResp.ProtoReflect.Descriptor instead.
func (*GetStatusResp) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResp) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetStatusResp) GetBoundAt() int64 {
	if x != nil {
		return x.BoundAt
	}
	return 0
}

func (x *GetStatusResp) GetRecoveryCodesRemaining() int32 {
	if x != nil {
		return x.RecoveryCodesRemaining
	}
	return 0
}

// UnbindTotpReq removes TOTP binding after verifying the user's code.
type UnbindTotpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	TotpCode      string                 `protobuf:"bytes,2,opt,name=totpCode,proto3" json:"totpCode"` // 6-digit TOTP code or 8-char recovery code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindTotpReq) Reset() {
	*x = UnbindTotpReq{}
	mi := &file_totp_totp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindTotpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindTotpReq) ProtoMessage() {}

func (x *UnbindTotpReq) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindTotpReq.ProtoReflect.Descriptor instead.
func (*UnbindTotpReq) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{8}
}

func (x *UnbindTotpReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UnbindTotpReq) GetTotpCode() string {
	if x != nil {
		return x.TotpCode
	}
	return ""
}

type UnbindTotpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindTotpResp) Reset() {
	*x = UnbindTotpResp{}
	mi := &file_totp_totp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindTotpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindTotpResp) ProtoMessage() {}

func (x *UnbindTotpResp) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindTotpResp.ProtoReflect.Descriptor instead.
func (*UnbindTotpResp) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{9}
}

// CreateMfaTokenReq is called by the auth service when a user passes primary
// authentication and has TOTP enabled. It returns a short-lived mfaToken to
// be sent back to the client as a placeholder for the second factor.
type CreateMfaTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMfaTokenReq) Reset() {
	*x = CreateMfaTokenReq{}
	mi := &file_totp_totp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMfaTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMfaTokenReq) ProtoMessage() {}

func (x *CreateMfaTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMfaTokenReq.ProtoReflect.Descriptor instead.
func (*CreateMfaTokenReq) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{10}
}

func (x *CreateMfaTokenReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CreateMfaTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MfaToken      string                 `protobuf:"bytes,1,opt,name=mfaToken,proto3" json:"mfaToken"`
	ExpireAt      int64                  `protobuf:"varint,2,opt,name=expireAt,proto3" json:"expireAt"` // Unix seconds (5 min from now)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMfaTokenResp) Reset() {
	*x = CreateMfaTokenResp{}
	mi := &file_totp_totp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMfaTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMfaTokenResp) ProtoMessage() {}

func (x *CreateMfaTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMfaTokenResp.ProtoReflect.Descriptor instead.
func (*CreateMfaTokenResp) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{11}
}

func (x *CreateMfaTokenResp) GetMfaToken() string {
	if x != nil {
		return x.MfaToken
	}
	return ""
}

func (x *CreateMfaTokenResp) GetExpireAt() int64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

// CheckTotpBoundReq is called by the auth service to decide whether to require MFA.
type CheckTotpBoundReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTotpBoundReq) Reset() {
	*x = CheckTotpBoundReq{}
	mi := &file_totp_totp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTotpBoundReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTotpBoundReq) ProtoMessage() {}

func (x *CheckTotpBoundReq) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTotpBoundReq.ProtoReflect.Descriptor instead.
func (*CheckTotpBoundReq) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{12}
}

func (x *CheckTotpBoundReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type CheckTotpBoundResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bound         bool                   `protobuf:"varint,1,opt,name=bound,proto3" json:"bound"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTotpBoundResp) Reset() {
	*x = CheckTotpBoundResp{}
	mi := &file_totp_totp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTotpBoundResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTotpBoundResp) ProtoMessage() {}

func (x *CheckTotpBoundResp) ProtoReflect() protoreflect.Message {
	mi := &file_totp_totp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTotpBoundResp.ProtoReflect.Descriptor instead.
func (*CheckTotpBoundResp) Descriptor() ([]byte, []int) {
	return file_totp_totp_proto_rawDescGZIP(), []int{13}
}

func (x *CheckTotpBoundResp) GetBound() bool {
	if x != nil {
		return x.Bound
	}
	return false
}

var File_totp_totp_proto protoreflect.FileDescriptor

const file_totp_totp_proto_rawDesc = "" +
	"\n" +
	"\x0ftotp/totp.proto\x12\vopenim.totp\"`\n" +
	"\fGetSecretReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12 \n" +
	"\vaccountName\x18\x03 \x01(\tR\vaccountName\"c\n" +
	"\rGetSecretResp\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1e\n" +
	"\n" +
	"otpAuthUrl\x18\x02 \x01(\tR\n" +
	"otpAuthUrl\x12\x1a\n" +
	"\bexpireAt\x18\x03 \x01(\x03R\bexpireAt\"A\n" +
	"\vBindTotpReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\btotpCode\x18\x02 \x01(\tR\btotpCode\"4\n" +
	"\fBindTotpResp\x12$\n" +
	"\rrecoveryCodes\x18\x01 \x03(\tR\rrecoveryCodes\"c\n" +
	"\rVerifyTotpReq\x12\x1a\n" +
	"\bmfaToken\x18\x01 \x01(\tR\bmfaToken\x12\x1a\n" +
	"\btotpCode\x18\x02 \x01(\tR\btotpCode\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\x05R\bplatform\"\x82\x01\n" +
	"\x0eVerifyTotpResp\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12*\n" +
	"\x10recoveryCodesLow\x18\x02 \x01(\bR\x10recoveryCodesLow\x12,\n" +
	"\x11recoveryCodesLeft\x18\x03 \x01(\x05R\x11recoveryCodesLeft\"&\n" +
	"\fGetStatusReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"{\n" +
	"\rGetStatusResp\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aboundAt\x18\x02 \x01(\x03R\aboundAt\x126\n" +
	"\x16recoveryCodesRemaining\x18\x03 \x01(\x05R\x16recoveryCodesRemaining\"C\n" +
	"\rUnbindTotpReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\btotpCode\x18\x02 \x01(\tR\btotpCode\"\x10\n" +
	"\x0eUnbindTotpResp\"+\n" +
	"\x11CreateMfaTokenReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"L\n" +
	"\x12CreateMfaTokenResp\x12\x1a\n" +
	"\bmfaToken\x18\x01 \x01(\tR\bmfaToken\x12\x1a\n" +
	"\bexpireAt\x18\x02 \x01(\x03R\bexpireAt\"+\n" +
	"\x11CheckTotpBoundReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"*\n" +
	"\x12CheckTotpBoundResp\x12\x14\n" +
	"\x05bound\x18\x01 \x01(\bR\x05bound2\x83\x04\n" +
	"\x04Totp\x12B\n" +
	"\tGetSecret\x12\x19.openim.totp.GetSecretReq\x1a\x1a.openim.totp.GetSecretResp\x12?\n" +
	"\bBindTotp\x12\x18.openim.totp.BindTotpReq\x1a\x19.openim.totp.BindTotpResp\x12E\n" +
	"\n" +
	"VerifyTotp\x12\x1a.openim.totp.VerifyTotpReq\x1a\x1b.openim.totp.VerifyTotpResp\x12B\n" +
	"\tGetStatus\x12\x19.openim.totp.GetStatusReq\x1a\x1a.openim.totp.GetStatusResp\x12E\n" +
	"\n" +
	"UnbindTotp\x12\x1a.openim.totp.UnbindTotpReq\x1a\x1b.openim.totp.UnbindTotpResp\x12Q\n" +
	"\x0eCreateMfaToken\x12\x1e.openim.totp.CreateMfaTokenReq\x1a\x1f.openim.totp.CreateMfaTokenResp\x12Q\n" +
	"\x0eCheckTotpBound\x12\x1e.openim.totp.CheckTotpBoundReq\x1a\x1f.openim.totp.CheckTotpBoundRespB$Z\"github.com/openimsdk/protocol/totpb\x06proto3"

var (
	file_totp_totp_proto_rawDescOnce sync.Once
	file_totp_totp_proto_rawDescData []byte
)

func file_totp_totp_proto_rawDescGZIP() []byte {
	file_totp_totp_proto_rawDescOnce.Do(func() {
		file_totp_totp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_totp_totp_proto_rawDesc), len(file_totp_totp_proto_rawDesc)))
	})
	return file_totp_totp_proto_rawDescData
}

var file_totp_totp_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_totp_totp_proto_goTypes = []any{
	(*GetSecretReq)(nil),       // 0: openim.totp.GetSecretReq
	(*GetSecretResp)(nil),      // 1: openim.totp.GetSecretResp
	(*BindTotpReq)(nil),        // 2: openim.totp.BindTotpReq
	(*BindTotpResp)(nil),       // 3: openim.totp.BindTotpResp
	(*VerifyTotpReq)(nil),      // 4: openim.totp.VerifyTotpReq
	(*VerifyTotpResp)(nil),     // 5: openim.totp.VerifyTotpResp
	(*GetStatusReq)(nil),       // 6: openim.totp.GetStatusReq
	(*GetStatusResp)(nil),      // 7: openim.totp.GetStatusResp
	(*UnbindTotpReq)(nil),      // 8: openim.totp.UnbindTotpReq
	(*UnbindTotpResp)(nil),     // 9: openim.totp.UnbindTotpResp
	(*CreateMfaTokenReq)(nil),  // 10: openim.totp.CreateMfaTokenReq
	(*CreateMfaTokenResp)(nil), // 11: openim.totp.CreateMfaTokenResp
	(*CheckTotpBoundReq)(nil),  // 12: openim.totp.CheckTotpBoundReq
	(*CheckTotpBoundResp)(nil), // 13: openim.totp.CheckTotpBoundResp
}
var file_totp_totp_proto_depIdxs = []int32{
	0,  // 0: openim.totp.Totp.GetSecret:input_type -> openim.totp.GetSecretReq
	2,  // 1: openim.totp.Totp.BindTotp:input_type -> openim.totp.BindTotpReq
	4,  // 2: openim.totp.Totp.VerifyTotp:input_type -> openim.totp.VerifyTotpReq
	6,  // 3: openim.totp.Totp.GetStatus:input_type -> openim.totp.GetStatusReq
	8,  // 4: openim.totp.Totp.UnbindTotp:input_type -> openim.totp.UnbindTotpReq
	10, // 5: openim.totp.Totp.CreateMfaToken:input_type -> openim.totp.CreateMfaTokenReq
	12, // 6: openim.totp.Totp.CheckTotpBound:input_type -> openim.totp.CheckTotpBoundReq
	1,  // 7: openim.totp.Totp.GetSecret:output_type -> openim.totp.GetSecretResp
	3,  // 8: openim.totp.Totp.BindTotp:output_type -> openim.totp.BindTotpResp
	5,  // 9: openim.totp.Totp.VerifyTotp:output_type -> openim.totp.VerifyTotpResp
	7,  // 10: openim.totp.Totp.GetStatus:output_type -> openim.totp.GetStatusResp
	9,  // 11: openim.totp.Totp.UnbindTotp:output_type -> openim.totp.UnbindTotpResp
	11, // 12: openim.totp.Totp.CreateMfaToken:output_type -> openim.totp.CreateMfaTokenResp
	13, // 13: openim.totp.Totp.CheckTotpBound:output_type -> openim.totp.CheckTotpBoundResp
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_totp_totp_proto_init() }
func file_totp_totp_proto_init() {
	if File_totp_totp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_totp_totp_proto_rawDesc), len(file_totp_totp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_totp_totp_proto_goTypes,
		DependencyIndexes: file_totp_totp_proto_depIdxs,
		MessageInfos:      file_totp_totp_proto_msgTypes,
	}.Build()
	File_totp_totp_proto = out.File
	file_totp_totp_proto_goTypes = nil
	file_totp_totp_proto_depIdxs = nil
}
