// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: totp.proto

package totp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Totp_GetSecret_FullMethodName      = "/openim.totp.Totp/GetSecret"
	Totp_BindTotp_FullMethodName       = "/openim.totp.Totp/BindTotp"
	Totp_VerifyTotp_FullMethodName     = "/openim.totp.Totp/VerifyTotp"
	Totp_GetStatus_FullMethodName      = "/openim.totp.Totp/GetStatus"
	Totp_UnbindTotp_FullMethodName     = "/openim.totp.Totp/UnbindTotp"
	Totp_CreateMfaToken_FullMethodName = "/openim.totp.Totp/CreateMfaToken"
	Totp_CheckTotpBound_FullMethodName = "/openim.totp.Totp/CheckTotpBound"
)

// TotpClient is the client API for Totp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TotpClient interface {
	GetSecret(ctx context.Context, in *GetSecretReq, opts ...grpc.CallOption) (*GetSecretResp, error)
	BindTotp(ctx context.Context, in *BindTotpReq, opts ...grpc.CallOption) (*BindTotpResp, error)
	VerifyTotp(ctx context.Context, in *VerifyTotpReq, opts ...grpc.CallOption) (*VerifyTotpResp, error)
	GetStatus(ctx context.Context, in *GetStatusReq, opts ...grpc.CallOption) (*GetStatusResp, error)
	UnbindTotp(ctx context.Context, in *UnbindTotpReq, opts ...grpc.CallOption) (*UnbindTotpResp, error)
	CreateMfaToken(ctx context.Context, in *CreateMfaTokenReq, opts ...grpc.CallOption) (*CreateMfaTokenResp, error)
	CheckTotpBound(ctx context.Context, in *CheckTotpBoundReq, opts ...grpc.CallOption) (*CheckTotpBoundResp, error)
}

type totpClient struct {
	cc grpc.ClientConnInterface
}

func NewTotpClient(cc grpc.ClientConnInterface) TotpClient {
	return &totpClient{cc}
}

func (c *totpClient) GetSecret(ctx context.Context, in *GetSecretReq, opts ...grpc.CallOption) (*GetSecretResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretResp)
	err := c.cc.Invoke(ctx, Totp_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *totpClient) BindTotp(ctx context.Context, in *BindTotpReq, opts ...grpc.CallOption) (*BindTotpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindTotpResp)
	err := c.cc.Invoke(ctx, Totp_BindTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *totpClient) VerifyTotp(ctx context.Context, in *VerifyTotpReq, opts ...grpc.CallOption) (*VerifyTotpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTotpResp)
	err := c.cc.Invoke(ctx, Totp_VerifyTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *totpClient) GetStatus(ctx context.Context, in *GetStatusReq, opts ...grpc.CallOption) (*GetStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResp)
	err := c.cc.Invoke(ctx, Totp_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *totpClient) UnbindTotp(ctx context.Context, in *UnbindTotpReq, opts ...grpc.CallOption) (*UnbindTotpResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindTotpResp)
	err := c.cc.Invoke(ctx, Totp_UnbindTotp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *totpClient) CreateMfaToken(ctx context.Context, in *CreateMfaTokenReq, opts ...grpc.CallOption) (*CreateMfaTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMfaTokenResp)
	err := c.cc.Invoke(ctx, Totp_CreateMfaToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *totpClient) CheckTotpBound(ctx context.Context, in *CheckTotpBoundReq, opts ...grpc.CallOption) (*CheckTotpBoundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTotpBoundResp)
	err := c.cc.Invoke(ctx, Totp_CheckTotpBound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TotpServer is the server API for Totp service.
// All implementations must embed UnimplementedTotpServer
// for forward compatibility.
type TotpServer interface {
	GetSecret(context.Context, *GetSecretReq) (*GetSecretResp, error)
	BindTotp(context.Context, *BindTotpReq) (*BindTotpResp, error)
	VerifyTotp(context.Context, *VerifyTotpReq) (*VerifyTotpResp, error)
	GetStatus(context.Context, *GetStatusReq) (*GetStatusResp, error)
	UnbindTotp(context.Context, *UnbindTotpReq) (*UnbindTotpResp, error)
	CreateMfaToken(context.Context, *CreateMfaTokenReq) (*CreateMfaTokenResp, error)
	CheckTotpBound(context.Context, *CheckTotpBoundReq) (*CheckTotpBoundResp, error)
	mustEmbedUnimplementedTotpServer()
}

// UnimplementedTotpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTotpServer struct{}

func (UnimplementedTotpServer) GetSecret(context.Context, *GetSecretReq) (*GetSecretResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedTotpServer) BindTotp(context.Context, *BindTotpReq) (*BindTotpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BindTotp not implemented")
}
func (UnimplementedTotpServer) VerifyTotp(context.Context, *VerifyTotpReq) (*VerifyTotpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyTotp not implemented")
}
func (UnimplementedTotpServer) GetStatus(context.Context, *GetStatusReq) (*GetStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTotpServer) UnbindTotp(context.Context, *UnbindTotpReq) (*UnbindTotpResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindTotp not implemented")
}
func (UnimplementedTotpServer) CreateMfaToken(context.Context, *CreateMfaTokenReq) (*CreateMfaTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMfaToken not implemented")
}
func (UnimplementedTotpServer) CheckTotpBound(context.Context, *CheckTotpBoundReq) (*CheckTotpBoundResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTotpBound not implemented")
}
func (UnimplementedTotpServer) mustEmbedUnimplementedTotpServer() {}
func (UnimplementedTotpServer) testEmbeddedByValue()              {}

// UnsafeTotpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TotpServer will
// result in compilation errors.
type UnsafeTotpServer interface {
	mustEmbedUnimplementedTotpServer()
}

func RegisterTotpServer(s grpc.ServiceRegistrar, srv TotpServer) {
	// If the following call panics, it indicates UnimplementedTotpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Totp_ServiceDesc, srv)
}

func _Totp_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TotpServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Totp_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TotpServer).GetSecret(ctx, req.(*GetSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Totp_BindTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindTotpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TotpServer).BindTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Totp_BindTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TotpServer).BindTotp(ctx, req.(*BindTotpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Totp_VerifyTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTotpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TotpServer).VerifyTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Totp_VerifyTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TotpServer).VerifyTotp(ctx, req.(*VerifyTotpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Totp_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TotpServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Totp_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TotpServer).GetStatus(ctx, req.(*GetStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Totp_UnbindTotp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindTotpReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TotpServer).UnbindTotp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Totp_UnbindTotp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TotpServer).UnbindTotp(ctx, req.(*UnbindTotpReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Totp_CreateMfaToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMfaTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TotpServer).CreateMfaToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Totp_CreateMfaToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TotpServer).CreateMfaToken(ctx, req.(*CreateMfaTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Totp_CheckTotpBound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTotpBoundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TotpServer).CheckTotpBound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Totp_CheckTotpBound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TotpServer).CheckTotpBound(ctx, req.(*CheckTotpBoundReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Totp_ServiceDesc is the grpc.ServiceDesc for Totp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Totp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.totp.Totp",
	HandlerType: (*TotpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecret",
			Handler:    _Totp_GetSecret_Handler,
		},
		{
			MethodName: "BindTotp",
			Handler:    _Totp_BindTotp_Handler,
		},
		{
			MethodName: "VerifyTotp",
			Handler:    _Totp_VerifyTotp_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Totp_GetStatus_Handler,
		},
		{
			MethodName: "UnbindTotp",
			Handler:    _Totp_UnbindTotp_Handler,
		},
		{
			MethodName: "CreateMfaToken",
			Handler:    _Totp_CreateMfaToken_Handler,
		},
		{
			MethodName: "CheckTotpBound",
			Handler:    _Totp_CheckTotpBound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "totp.proto",
}
