// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: redpacket/redpacket.proto

package redpacket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedPacket_CreateOrder_FullMethodName              = "/openim.redpacket.RedPacket/CreateOrder"
	RedPacket_CreatedCallback_FullMethodName          = "/openim.redpacket.RedPacket/CreatedCallback"
	RedPacket_GetDetail_FullMethodName                = "/openim.redpacket.RedPacket/GetDetail"
	RedPacket_IssueClaimSign_FullMethodName           = "/openim.redpacket.RedPacket/IssueClaimSign"
	RedPacket_ClaimResult_FullMethodName              = "/openim.redpacket.RedPacket/ClaimResult"
	RedPacket_IssueWalletBindChallenge_FullMethodName = "/openim.redpacket.RedPacket/IssueWalletBindChallenge"
	RedPacket_ConfirmWalletBind_FullMethodName        = "/openim.redpacket.RedPacket/ConfirmWalletBind"
	RedPacket_GetWalletBinding_FullMethodName         = "/openim.redpacket.RedPacket/GetWalletBinding"
	RedPacket_SetSigner_FullMethodName                = "/openim.redpacket.RedPacket/SetSigner"
	RedPacket_SetToken_FullMethodName                 = "/openim.redpacket.RedPacket/SetToken"
	RedPacket_SetExpiry_FullMethodName                = "/openim.redpacket.RedPacket/SetExpiry"
	RedPacket_SetAllowAllTokens_FullMethodName        = "/openim.redpacket.RedPacket/SetAllowAllTokens"
	RedPacket_SetNativeTokenEnabled_FullMethodName    = "/openim.redpacket.RedPacket/SetNativeTokenEnabled"
	RedPacket_ParseTxEvents_FullMethodName            = "/openim.redpacket.RedPacket/ParseTxEvents"
)

// RedPacketClient is the client API for RedPacket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedPacketClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
	CreatedCallback(ctx context.Context, in *CreatedCallbackReq, opts ...grpc.CallOption) (*CreatedCallbackResp, error)
	GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*GetDetailResp, error)
	IssueClaimSign(ctx context.Context, in *IssueClaimSignReq, opts ...grpc.CallOption) (*IssueClaimSignResp, error)
	ClaimResult(ctx context.Context, in *ClaimResultReq, opts ...grpc.CallOption) (*ClaimResultResp, error)
	IssueWalletBindChallenge(ctx context.Context, in *IssueWalletBindChallengeReq, opts ...grpc.CallOption) (*IssueWalletBindChallengeResp, error)
	ConfirmWalletBind(ctx context.Context, in *ConfirmWalletBindReq, opts ...grpc.CallOption) (*ConfirmWalletBindResp, error)
	GetWalletBinding(ctx context.Context, in *GetWalletBindingReq, opts ...grpc.CallOption) (*GetWalletBindingResp, error)
	SetSigner(ctx context.Context, in *SetSignerReq, opts ...grpc.CallOption) (*SetSignerResp, error)
	SetToken(ctx context.Context, in *SetTokenReq, opts ...grpc.CallOption) (*SetTokenResp, error)
	SetExpiry(ctx context.Context, in *SetExpiryReq, opts ...grpc.CallOption) (*SetExpiryResp, error)
	SetAllowAllTokens(ctx context.Context, in *SetAllowAllTokensReq, opts ...grpc.CallOption) (*SetAllowAllTokensResp, error)
	SetNativeTokenEnabled(ctx context.Context, in *SetNativeTokenEnabledReq, opts ...grpc.CallOption) (*SetNativeTokenEnabledResp, error)
	ParseTxEvents(ctx context.Context, in *ParseTxEventsReq, opts ...grpc.CallOption) (*ParseTxEventsResp, error)
}

type redPacketClient struct {
	cc grpc.ClientConnInterface
}

func NewRedPacketClient(cc grpc.ClientConnInterface) RedPacketClient {
	return &redPacketClient{cc}
}

func (c *redPacketClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, RedPacket_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) CreatedCallback(ctx context.Context, in *CreatedCallbackReq, opts ...grpc.CallOption) (*CreatedCallbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatedCallbackResp)
	err := c.cc.Invoke(ctx, RedPacket_CreatedCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*GetDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailResp)
	err := c.cc.Invoke(ctx, RedPacket_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) IssueClaimSign(ctx context.Context, in *IssueClaimSignReq, opts ...grpc.CallOption) (*IssueClaimSignResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueClaimSignResp)
	err := c.cc.Invoke(ctx, RedPacket_IssueClaimSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) ClaimResult(ctx context.Context, in *ClaimResultReq, opts ...grpc.CallOption) (*ClaimResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResultResp)
	err := c.cc.Invoke(ctx, RedPacket_ClaimResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) IssueWalletBindChallenge(ctx context.Context, in *IssueWalletBindChallengeReq, opts ...grpc.CallOption) (*IssueWalletBindChallengeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueWalletBindChallengeResp)
	err := c.cc.Invoke(ctx, RedPacket_IssueWalletBindChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) ConfirmWalletBind(ctx context.Context, in *ConfirmWalletBindReq, opts ...grpc.CallOption) (*ConfirmWalletBindResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmWalletBindResp)
	err := c.cc.Invoke(ctx, RedPacket_ConfirmWalletBind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) GetWalletBinding(ctx context.Context, in *GetWalletBindingReq, opts ...grpc.CallOption) (*GetWalletBindingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletBindingResp)
	err := c.cc.Invoke(ctx, RedPacket_GetWalletBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetSigner(ctx context.Context, in *SetSignerReq, opts ...grpc.CallOption) (*SetSignerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSignerResp)
	err := c.cc.Invoke(ctx, RedPacket_SetSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetToken(ctx context.Context, in *SetTokenReq, opts ...grpc.CallOption) (*SetTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTokenResp)
	err := c.cc.Invoke(ctx, RedPacket_SetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetExpiry(ctx context.Context, in *SetExpiryReq, opts ...grpc.CallOption) (*SetExpiryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetExpiryResp)
	err := c.cc.Invoke(ctx, RedPacket_SetExpiry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetAllowAllTokens(ctx context.Context, in *SetAllowAllTokensReq, opts ...grpc.CallOption) (*SetAllowAllTokensResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAllowAllTokensResp)
	err := c.cc.Invoke(ctx, RedPacket_SetAllowAllTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetNativeTokenEnabled(ctx context.Context, in *SetNativeTokenEnabledReq, opts ...grpc.CallOption) (*SetNativeTokenEnabledResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNativeTokenEnabledResp)
	err := c.cc.Invoke(ctx, RedPacket_SetNativeTokenEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) ParseTxEvents(ctx context.Context, in *ParseTxEventsReq, opts ...grpc.CallOption) (*ParseTxEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseTxEventsResp)
	err := c.cc.Invoke(ctx, RedPacket_ParseTxEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedPacketServer is the server API for RedPacket service.
// All implementations must embed UnimplementedRedPacketServer
// for forward compatibility.
type RedPacketServer interface {
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	CreatedCallback(context.Context, *CreatedCallbackReq) (*CreatedCallbackResp, error)
	GetDetail(context.Context, *GetDetailReq) (*GetDetailResp, error)
	IssueClaimSign(context.Context, *IssueClaimSignReq) (*IssueClaimSignResp, error)
	ClaimResult(context.Context, *ClaimResultReq) (*ClaimResultResp, error)
	IssueWalletBindChallenge(context.Context, *IssueWalletBindChallengeReq) (*IssueWalletBindChallengeResp, error)
	ConfirmWalletBind(context.Context, *ConfirmWalletBindReq) (*ConfirmWalletBindResp, error)
	GetWalletBinding(context.Context, *GetWalletBindingReq) (*GetWalletBindingResp, error)
	SetSigner(context.Context, *SetSignerReq) (*SetSignerResp, error)
	SetToken(context.Context, *SetTokenReq) (*SetTokenResp, error)
	SetExpiry(context.Context, *SetExpiryReq) (*SetExpiryResp, error)
	SetAllowAllTokens(context.Context, *SetAllowAllTokensReq) (*SetAllowAllTokensResp, error)
	SetNativeTokenEnabled(context.Context, *SetNativeTokenEnabledReq) (*SetNativeTokenEnabledResp, error)
	ParseTxEvents(context.Context, *ParseTxEventsReq) (*ParseTxEventsResp, error)
	mustEmbedUnimplementedRedPacketServer()
}

// UnimplementedRedPacketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedPacketServer struct{}

func (UnimplementedRedPacketServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedRedPacketServer) CreatedCallback(context.Context, *CreatedCallbackReq) (*CreatedCallbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatedCallback not implemented")
}
func (UnimplementedRedPacketServer) GetDetail(context.Context, *GetDetailReq) (*GetDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedRedPacketServer) IssueClaimSign(context.Context, *IssueClaimSignReq) (*IssueClaimSignResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueClaimSign not implemented")
}
func (UnimplementedRedPacketServer) ClaimResult(context.Context, *ClaimResultReq) (*ClaimResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimResult not implemented")
}
func (UnimplementedRedPacketServer) IssueWalletBindChallenge(context.Context, *IssueWalletBindChallengeReq) (*IssueWalletBindChallengeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueWalletBindChallenge not implemented")
}
func (UnimplementedRedPacketServer) ConfirmWalletBind(context.Context, *ConfirmWalletBindReq) (*ConfirmWalletBindResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmWalletBind not implemented")
}
func (UnimplementedRedPacketServer) GetWalletBinding(context.Context, *GetWalletBindingReq) (*GetWalletBindingResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletBinding not implemented")
}
func (UnimplementedRedPacketServer) SetSigner(context.Context, *SetSignerReq) (*SetSignerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSigner not implemented")
}
func (UnimplementedRedPacketServer) SetToken(context.Context, *SetTokenReq) (*SetTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetToken not implemented")
}
func (UnimplementedRedPacketServer) SetExpiry(context.Context, *SetExpiryReq) (*SetExpiryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetExpiry not implemented")
}
func (UnimplementedRedPacketServer) SetAllowAllTokens(context.Context, *SetAllowAllTokensReq) (*SetAllowAllTokensResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAllowAllTokens not implemented")
}
func (UnimplementedRedPacketServer) SetNativeTokenEnabled(context.Context, *SetNativeTokenEnabledReq) (*SetNativeTokenEnabledResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNativeTokenEnabled not implemented")
}
func (UnimplementedRedPacketServer) ParseTxEvents(context.Context, *ParseTxEventsReq) (*ParseTxEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseTxEvents not implemented")
}
func (UnimplementedRedPacketServer) mustEmbedUnimplementedRedPacketServer() {}
func (UnimplementedRedPacketServer) testEmbeddedByValue()                   {}

// UnsafeRedPacketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedPacketServer will
// result in compilation errors.
type UnsafeRedPacketServer interface {
	mustEmbedUnimplementedRedPacketServer()
}

func RegisterRedPacketServer(s grpc.ServiceRegistrar, srv RedPacketServer) {
	// If the following call panics, it indicates UnimplementedRedPacketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedPacket_ServiceDesc, srv)
}

func _RedPacket_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_CreatedCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatedCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).CreatedCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_CreatedCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).CreatedCallback(ctx, req.(*CreatedCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).GetDetail(ctx, req.(*GetDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_IssueClaimSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueClaimSignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).IssueClaimSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_IssueClaimSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).IssueClaimSign(ctx, req.(*IssueClaimSignReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_ClaimResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).ClaimResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_ClaimResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).ClaimResult(ctx, req.(*ClaimResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_IssueWalletBindChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueWalletBindChallengeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).IssueWalletBindChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_IssueWalletBindChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).IssueWalletBindChallenge(ctx, req.(*IssueWalletBindChallengeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_ConfirmWalletBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmWalletBindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).ConfirmWalletBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_ConfirmWalletBind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).ConfirmWalletBind(ctx, req.(*ConfirmWalletBindReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_GetWalletBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletBindingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).GetWalletBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_GetWalletBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).GetWalletBinding(ctx, req.(*GetWalletBindingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSignerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetSigner(ctx, req.(*SetSignerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetToken(ctx, req.(*SetTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetExpiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExpiryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetExpiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetExpiry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetExpiry(ctx, req.(*SetExpiryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetAllowAllTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAllowAllTokensReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetAllowAllTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetAllowAllTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetAllowAllTokens(ctx, req.(*SetAllowAllTokensReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetNativeTokenEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNativeTokenEnabledReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetNativeTokenEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetNativeTokenEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetNativeTokenEnabled(ctx, req.(*SetNativeTokenEnabledReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_ParseTxEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseTxEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).ParseTxEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_ParseTxEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).ParseTxEvents(ctx, req.(*ParseTxEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RedPacket_ServiceDesc is the grpc.ServiceDesc for RedPacket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedPacket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.redpacket.RedPacket",
	HandlerType: (*RedPacketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _RedPacket_CreateOrder_Handler,
		},
		{
			MethodName: "CreatedCallback",
			Handler:    _RedPacket_CreatedCallback_Handler,
		},
		{
			MethodName: "GetDetail",
			Handler:    _RedPacket_GetDetail_Handler,
		},
		{
			MethodName: "IssueClaimSign",
			Handler:    _RedPacket_IssueClaimSign_Handler,
		},
		{
			MethodName: "ClaimResult",
			Handler:    _RedPacket_ClaimResult_Handler,
		},
		{
			MethodName: "IssueWalletBindChallenge",
			Handler:    _RedPacket_IssueWalletBindChallenge_Handler,
		},
		{
			MethodName: "ConfirmWalletBind",
			Handler:    _RedPacket_ConfirmWalletBind_Handler,
		},
		{
			MethodName: "GetWalletBinding",
			Handler:    _RedPacket_GetWalletBinding_Handler,
		},
		{
			MethodName: "SetSigner",
			Handler:    _RedPacket_SetSigner_Handler,
		},
		{
			MethodName: "SetToken",
			Handler:    _RedPacket_SetToken_Handler,
		},
		{
			MethodName: "SetExpiry",
			Handler:    _RedPacket_SetExpiry_Handler,
		},
		{
			MethodName: "SetAllowAllTokens",
			Handler:    _RedPacket_SetAllowAllTokens_Handler,
		},
		{
			MethodName: "SetNativeTokenEnabled",
			Handler:    _RedPacket_SetNativeTokenEnabled_Handler,
		},
		{
			MethodName: "ParseTxEvents",
			Handler:    _RedPacket_ParseTxEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redpacket/redpacket.proto",
}
