// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: redpacket/redpacket.proto

package redpacket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedPacket_CreateOrder_FullMethodName       = "/openim.redpacket.RedPacket/createOrder"
	RedPacket_CreatedCallback_FullMethodName   = "/openim.redpacket.RedPacket/createdCallback"
	RedPacket_GetDetail_FullMethodName         = "/openim.redpacket.RedPacket/getDetail"
	RedPacket_ClaimSign_FullMethodName         = "/openim.redpacket.RedPacket/claimSign"
	RedPacket_ClaimResult_FullMethodName       = "/openim.redpacket.RedPacket/claimResult"
	RedPacket_SetSigner_FullMethodName         = "/openim.redpacket.RedPacket/setSigner"
	RedPacket_SetToken_FullMethodName          = "/openim.redpacket.RedPacket/setToken"
	RedPacket_SetExpiry_FullMethodName         = "/openim.redpacket.RedPacket/setExpiry"
	RedPacket_SetAllowAllTokens_FullMethodName = "/openim.redpacket.RedPacket/setAllowAllTokens"
	RedPacket_SetNativeToken_FullMethodName    = "/openim.redpacket.RedPacket/setNativeToken"
	RedPacket_ParseTxEvents_FullMethodName     = "/openim.redpacket.RedPacket/parseTxEvents"
)

// RedPacketClient is the client API for RedPacket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedPacketClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
	CreatedCallback(ctx context.Context, in *CreatedCallbackReq, opts ...grpc.CallOption) (*CreatedCallbackResp, error)
	GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*GetDetailResp, error)
	ClaimSign(ctx context.Context, in *ClaimSignReq, opts ...grpc.CallOption) (*ClaimSignResp, error)
	ClaimResult(ctx context.Context, in *ClaimResultReq, opts ...grpc.CallOption) (*ClaimResultResp, error)
	SetSigner(ctx context.Context, in *SetSignerReq, opts ...grpc.CallOption) (*TxResp, error)
	SetToken(ctx context.Context, in *SetTokenReq, opts ...grpc.CallOption) (*TxResp, error)
	SetExpiry(ctx context.Context, in *SetExpiryReq, opts ...grpc.CallOption) (*TxResp, error)
	SetAllowAllTokens(ctx context.Context, in *SetAllowAllTokensReq, opts ...grpc.CallOption) (*TxResp, error)
	SetNativeToken(ctx context.Context, in *SetNativeTokenReq, opts ...grpc.CallOption) (*TxResp, error)
	ParseTxEvents(ctx context.Context, in *ParseTxEventsReq, opts ...grpc.CallOption) (*ParseTxEventsResp, error)
}

type redPacketClient struct {
	cc grpc.ClientConnInterface
}

func NewRedPacketClient(cc grpc.ClientConnInterface) RedPacketClient {
	return &redPacketClient{cc}
}

func (c *redPacketClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResp)
	err := c.cc.Invoke(ctx, RedPacket_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) CreatedCallback(ctx context.Context, in *CreatedCallbackReq, opts ...grpc.CallOption) (*CreatedCallbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatedCallbackResp)
	err := c.cc.Invoke(ctx, RedPacket_CreatedCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) GetDetail(ctx context.Context, in *GetDetailReq, opts ...grpc.CallOption) (*GetDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailResp)
	err := c.cc.Invoke(ctx, RedPacket_GetDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) ClaimSign(ctx context.Context, in *ClaimSignReq, opts ...grpc.CallOption) (*ClaimSignResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimSignResp)
	err := c.cc.Invoke(ctx, RedPacket_ClaimSign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) ClaimResult(ctx context.Context, in *ClaimResultReq, opts ...grpc.CallOption) (*ClaimResultResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResultResp)
	err := c.cc.Invoke(ctx, RedPacket_ClaimResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetSigner(ctx context.Context, in *SetSignerReq, opts ...grpc.CallOption) (*TxResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxResp)
	err := c.cc.Invoke(ctx, RedPacket_SetSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetToken(ctx context.Context, in *SetTokenReq, opts ...grpc.CallOption) (*TxResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxResp)
	err := c.cc.Invoke(ctx, RedPacket_SetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetExpiry(ctx context.Context, in *SetExpiryReq, opts ...grpc.CallOption) (*TxResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxResp)
	err := c.cc.Invoke(ctx, RedPacket_SetExpiry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetAllowAllTokens(ctx context.Context, in *SetAllowAllTokensReq, opts ...grpc.CallOption) (*TxResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxResp)
	err := c.cc.Invoke(ctx, RedPacket_SetAllowAllTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) SetNativeToken(ctx context.Context, in *SetNativeTokenReq, opts ...grpc.CallOption) (*TxResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TxResp)
	err := c.cc.Invoke(ctx, RedPacket_SetNativeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redPacketClient) ParseTxEvents(ctx context.Context, in *ParseTxEventsReq, opts ...grpc.CallOption) (*ParseTxEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseTxEventsResp)
	err := c.cc.Invoke(ctx, RedPacket_ParseTxEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedPacketServer is the server API for RedPacket service.
// All implementations must embed UnimplementedRedPacketServer
// for forward compatibility.
type RedPacketServer interface {
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error)
	CreatedCallback(context.Context, *CreatedCallbackReq) (*CreatedCallbackResp, error)
	GetDetail(context.Context, *GetDetailReq) (*GetDetailResp, error)
	ClaimSign(context.Context, *ClaimSignReq) (*ClaimSignResp, error)
	ClaimResult(context.Context, *ClaimResultReq) (*ClaimResultResp, error)
	SetSigner(context.Context, *SetSignerReq) (*TxResp, error)
	SetToken(context.Context, *SetTokenReq) (*TxResp, error)
	SetExpiry(context.Context, *SetExpiryReq) (*TxResp, error)
	SetAllowAllTokens(context.Context, *SetAllowAllTokensReq) (*TxResp, error)
	SetNativeToken(context.Context, *SetNativeTokenReq) (*TxResp, error)
	ParseTxEvents(context.Context, *ParseTxEventsReq) (*ParseTxEventsResp, error)
	mustEmbedUnimplementedRedPacketServer()
}

// UnimplementedRedPacketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedPacketServer struct{}

func (UnimplementedRedPacketServer) CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedRedPacketServer) CreatedCallback(context.Context, *CreatedCallbackReq) (*CreatedCallbackResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatedCallback not implemented")
}
func (UnimplementedRedPacketServer) GetDetail(context.Context, *GetDetailReq) (*GetDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetail not implemented")
}
func (UnimplementedRedPacketServer) ClaimSign(context.Context, *ClaimSignReq) (*ClaimSignResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimSign not implemented")
}
func (UnimplementedRedPacketServer) ClaimResult(context.Context, *ClaimResultReq) (*ClaimResultResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimResult not implemented")
}
func (UnimplementedRedPacketServer) SetSigner(context.Context, *SetSignerReq) (*TxResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSigner not implemented")
}
func (UnimplementedRedPacketServer) SetToken(context.Context, *SetTokenReq) (*TxResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetToken not implemented")
}
func (UnimplementedRedPacketServer) SetExpiry(context.Context, *SetExpiryReq) (*TxResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetExpiry not implemented")
}
func (UnimplementedRedPacketServer) SetAllowAllTokens(context.Context, *SetAllowAllTokensReq) (*TxResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAllowAllTokens not implemented")
}
func (UnimplementedRedPacketServer) SetNativeToken(context.Context, *SetNativeTokenReq) (*TxResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNativeToken not implemented")
}
func (UnimplementedRedPacketServer) ParseTxEvents(context.Context, *ParseTxEventsReq) (*ParseTxEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseTxEvents not implemented")
}
func (UnimplementedRedPacketServer) mustEmbedUnimplementedRedPacketServer() {}
func (UnimplementedRedPacketServer) testEmbeddedByValue()                   {}

// UnsafeRedPacketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedPacketServer will
// result in compilation errors.
type UnsafeRedPacketServer interface {
	mustEmbedUnimplementedRedPacketServer()
}

func RegisterRedPacketServer(s grpc.ServiceRegistrar, srv RedPacketServer) {
	// If the following call panics, it indicates UnimplementedRedPacketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedPacket_ServiceDesc, srv)
}

func _RedPacket_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_CreatedCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatedCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).CreatedCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_CreatedCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).CreatedCallback(ctx, req.(*CreatedCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_GetDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).GetDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_GetDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).GetDetail(ctx, req.(*GetDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_ClaimSign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimSignReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).ClaimSign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_ClaimSign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).ClaimSign(ctx, req.(*ClaimSignReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_ClaimResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).ClaimResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_ClaimResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).ClaimResult(ctx, req.(*ClaimResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSignerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetSigner(ctx, req.(*SetSignerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetToken(ctx, req.(*SetTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetExpiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExpiryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetExpiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetExpiry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetExpiry(ctx, req.(*SetExpiryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetAllowAllTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAllowAllTokensReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetAllowAllTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetAllowAllTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetAllowAllTokens(ctx, req.(*SetAllowAllTokensReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_SetNativeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNativeTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).SetNativeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_SetNativeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).SetNativeToken(ctx, req.(*SetNativeTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedPacket_ParseTxEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseTxEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedPacketServer).ParseTxEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedPacket_ParseTxEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedPacketServer).ParseTxEvents(ctx, req.(*ParseTxEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RedPacket_ServiceDesc is the grpc.ServiceDesc for RedPacket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedPacket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.redpacket.RedPacket",
	HandlerType: (*RedPacketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createOrder",
			Handler:    _RedPacket_CreateOrder_Handler,
		},
		{
			MethodName: "createdCallback",
			Handler:    _RedPacket_CreatedCallback_Handler,
		},
		{
			MethodName: "getDetail",
			Handler:    _RedPacket_GetDetail_Handler,
		},
		{
			MethodName: "claimSign",
			Handler:    _RedPacket_ClaimSign_Handler,
		},
		{
			MethodName: "claimResult",
			Handler:    _RedPacket_ClaimResult_Handler,
		},
		{
			MethodName: "setSigner",
			Handler:    _RedPacket_SetSigner_Handler,
		},
		{
			MethodName: "setToken",
			Handler:    _RedPacket_SetToken_Handler,
		},
		{
			MethodName: "setExpiry",
			Handler:    _RedPacket_SetExpiry_Handler,
		},
		{
			MethodName: "setAllowAllTokens",
			Handler:    _RedPacket_SetAllowAllTokens_Handler,
		},
		{
			MethodName: "setNativeToken",
			Handler:    _RedPacket_SetNativeToken_Handler,
		},
		{
			MethodName: "parseTxEvents",
			Handler:    _RedPacket_ParseTxEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "redpacket/redpacket.proto",
}
