// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: redpacket/redpacket.proto

package redpacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorUserId string                 `protobuf:"bytes,1,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id"`
	CreatorWallet string                 `protobuf:"bytes,2,opt,name=creator_wallet,json=creatorWallet,proto3" json:"creator_wallet"`
	PacketType    int32                  `protobuf:"varint,3,opt,name=packet_type,json=packetType,proto3" json:"packet_type"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token"`
	TotalAmount   string                 `protobuf:"bytes,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount"`
	TotalShares   int32                  `protobuf:"varint,6,opt,name=total_shares,json=totalShares,proto3" json:"total_shares"`
	ExpiryAt      int64                  `protobuf:"varint,7,opt,name=expiry_at,json=expiryAt,proto3" json:"expiry_at"`
	Chain         string                 `protobuf:"bytes,8,opt,name=chain,proto3" json:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderReq) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *CreateOrderReq) GetCreatorWallet() string {
	if x != nil {
		return x.CreatorWallet
	}
	return ""
}

func (x *CreateOrderReq) GetPacketType() int32 {
	if x != nil {
		return x.PacketType
	}
	return 0
}

func (x *CreateOrderReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateOrderReq) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *CreateOrderReq) GetTotalShares() int32 {
	if x != nil {
		return x.TotalShares
	}
	return 0
}

func (x *CreateOrderReq) GetExpiryAt() int64 {
	if x != nil {
		return x.ExpiryAt
	}
	return 0
}

func (x *CreateOrderReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_redpacket_redpacket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResp) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

type CreatedCallbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         string                 `protobuf:"bytes,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash"`
	PacketId      string                 `protobuf:"bytes,3,opt,name=packet_id,json=packetId,proto3" json:"packet_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedCallbackReq) Reset() {
	*x = CreatedCallbackReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedCallbackReq) ProtoMessage() {}

func (x *CreatedCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedCallbackReq.ProtoReflect.Descriptor instead.
func (*CreatedCallbackReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{2}
}

func (x *CreatedCallbackReq) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *CreatedCallbackReq) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *CreatedCallbackReq) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

type CreatedCallbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedCallbackResp) Reset() {
	*x = CreatedCallbackResp{}
	mi := &file_redpacket_redpacket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedCallbackResp) ProtoMessage() {}

func (x *CreatedCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedCallbackResp.ProtoReflect.Descriptor instead.
func (*CreatedCallbackResp) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{3}
}

func (x *CreatedCallbackResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      string                 `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailReq) Reset() {
	*x = GetDetailReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailReq) ProtoMessage() {}

func (x *GetDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailReq.ProtoReflect.Descriptor instead.
func (*GetDetailReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{4}
}

func (x *GetDetailReq) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

type RedPacketRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	BizId           string                 `protobuf:"bytes,2,opt,name=biz_id,json=bizId,proto3" json:"biz_id"`
	PacketId        string                 `protobuf:"bytes,3,opt,name=packet_id,json=packetId,proto3" json:"packet_id"`
	ChainId         int64                  `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id"`
	ContractAddress string                 `protobuf:"bytes,5,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address"`
	CreatorUserId   string                 `protobuf:"bytes,6,opt,name=creator_user_id,json=creatorUserId,proto3" json:"creator_user_id"`
	CreatorWallet   string                 `protobuf:"bytes,7,opt,name=creator_wallet,json=creatorWallet,proto3" json:"creator_wallet"`
	PacketType      int32                  `protobuf:"varint,8,opt,name=packet_type,json=packetType,proto3" json:"packet_type"`
	Token           string                 `protobuf:"bytes,9,opt,name=token,proto3" json:"token"`
	TotalAmount     string                 `protobuf:"bytes,10,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount"`
	TotalShares     int32                  `protobuf:"varint,11,opt,name=total_shares,json=totalShares,proto3" json:"total_shares"`
	ExpiryAt        int64                  `protobuf:"varint,12,opt,name=expiry_at,json=expiryAt,proto3" json:"expiry_at"`
	TxHash          string                 `protobuf:"bytes,13,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash"`
	Status          string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status"`
	Chain           string                 `protobuf:"bytes,15,opt,name=chain,proto3" json:"chain"`
	CreatedAt       int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt       int64                  `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RedPacketRecord) Reset() {
	*x = RedPacketRecord{}
	mi := &file_redpacket_redpacket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedPacketRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedPacketRecord) ProtoMessage() {}

func (x *RedPacketRecord) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedPacketRecord.ProtoReflect.Descriptor instead.
func (*RedPacketRecord) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{5}
}

func (x *RedPacketRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RedPacketRecord) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

func (x *RedPacketRecord) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *RedPacketRecord) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *RedPacketRecord) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *RedPacketRecord) GetCreatorUserId() string {
	if x != nil {
		return x.CreatorUserId
	}
	return ""
}

func (x *RedPacketRecord) GetCreatorWallet() string {
	if x != nil {
		return x.CreatorWallet
	}
	return ""
}

func (x *RedPacketRecord) GetPacketType() int32 {
	if x != nil {
		return x.PacketType
	}
	return 0
}

func (x *RedPacketRecord) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RedPacketRecord) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *RedPacketRecord) GetTotalShares() int32 {
	if x != nil {
		return x.TotalShares
	}
	return 0
}

func (x *RedPacketRecord) GetExpiryAt() int64 {
	if x != nil {
		return x.ExpiryAt
	}
	return 0
}

func (x *RedPacketRecord) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *RedPacketRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RedPacketRecord) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *RedPacketRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RedPacketRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ClaimRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	PacketId      string                 `protobuf:"bytes,2,opt,name=packet_id,json=packetId,proto3" json:"packet_id"`
	ClaimerWallet string                 `protobuf:"bytes,3,opt,name=claimer_wallet,json=claimerWallet,proto3" json:"claimer_wallet"`
	AuthNonce     string                 `protobuf:"bytes,4,opt,name=auth_nonce,json=authNonce,proto3" json:"auth_nonce"`
	ClaimTxHash   string                 `protobuf:"bytes,5,opt,name=claim_tx_hash,json=claimTxHash,proto3" json:"claim_tx_hash"`
	ClaimedAmount string                 `protobuf:"bytes,6,opt,name=claimed_amount,json=claimedAmount,proto3" json:"claimed_amount"`
	BlockNumber   int64                  `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRecord) Reset() {
	*x = ClaimRecord{}
	mi := &file_redpacket_redpacket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRecord) ProtoMessage() {}

func (x *ClaimRecord) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRecord.ProtoReflect.Descriptor instead.
func (*ClaimRecord) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClaimRecord) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *ClaimRecord) GetClaimerWallet() string {
	if x != nil {
		return x.ClaimerWallet
	}
	return ""
}

func (x *ClaimRecord) GetAuthNonce() string {
	if x != nil {
		return x.AuthNonce
	}
	return ""
}

func (x *ClaimRecord) GetClaimTxHash() string {
	if x != nil {
		return x.ClaimTxHash
	}
	return ""
}

func (x *ClaimRecord) GetClaimedAmount() string {
	if x != nil {
		return x.ClaimedAmount
	}
	return ""
}

func (x *ClaimRecord) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ClaimRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ClaimRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ClaimRecord) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizRecord     *RedPacketRecord       `protobuf:"bytes,1,opt,name=biz_record,json=bizRecord,proto3" json:"biz_record"`
	Claims        []*ClaimRecord         `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailResp) Reset() {
	*x = GetDetailResp{}
	mi := &file_redpacket_redpacket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailResp) ProtoMessage() {}

func (x *GetDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailResp.ProtoReflect.Descriptor instead.
func (*GetDetailResp) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{7}
}

func (x *GetDetailResp) GetBizRecord() *RedPacketRecord {
	if x != nil {
		return x.BizRecord
	}
	return nil
}

func (x *GetDetailResp) GetClaims() []*ClaimRecord {
	if x != nil {
		return x.Claims
	}
	return nil
}

type ClaimSignReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      string                 `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id"`
	Claimer       string                 `protobuf:"bytes,2,opt,name=claimer,proto3" json:"claimer"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id"`
	RandomSeed    string                 `protobuf:"bytes,4,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimSignReq) Reset() {
	*x = ClaimSignReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimSignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSignReq) ProtoMessage() {}

func (x *ClaimSignReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSignReq.ProtoReflect.Descriptor instead.
func (*ClaimSignReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimSignReq) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *ClaimSignReq) GetClaimer() string {
	if x != nil {
		return x.Claimer
	}
	return ""
}

func (x *ClaimSignReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClaimSignReq) GetRandomSeed() string {
	if x != nil {
		return x.RandomSeed
	}
	return ""
}

type ClaimSignResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthNonce     string                 `protobuf:"bytes,1,opt,name=auth_nonce,json=authNonce,proto3" json:"auth_nonce"`
	Deadline      int64                  `protobuf:"varint,2,opt,name=deadline,proto3" json:"deadline"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature"`
	RandomSeed    string                 `protobuf:"bytes,4,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimSignResp) Reset() {
	*x = ClaimSignResp{}
	mi := &file_redpacket_redpacket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimSignResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimSignResp) ProtoMessage() {}

func (x *ClaimSignResp) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimSignResp.ProtoReflect.Descriptor instead.
func (*ClaimSignResp) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{9}
}

func (x *ClaimSignResp) GetAuthNonce() string {
	if x != nil {
		return x.AuthNonce
	}
	return ""
}

func (x *ClaimSignResp) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *ClaimSignResp) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ClaimSignResp) GetRandomSeed() string {
	if x != nil {
		return x.RandomSeed
	}
	return ""
}

type ClaimResultReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      string                 `protobuf:"bytes,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id"`
	ClaimerWallet string                 `protobuf:"bytes,2,opt,name=claimer_wallet,json=claimerWallet,proto3" json:"claimer_wallet"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash"`
	AuthNonce     string                 `protobuf:"bytes,4,opt,name=auth_nonce,json=authNonce,proto3" json:"auth_nonce"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResultReq) Reset() {
	*x = ClaimResultReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResultReq) ProtoMessage() {}

func (x *ClaimResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResultReq.ProtoReflect.Descriptor instead.
func (*ClaimResultReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{10}
}

func (x *ClaimResultReq) GetPacketId() string {
	if x != nil {
		return x.PacketId
	}
	return ""
}

func (x *ClaimResultReq) GetClaimerWallet() string {
	if x != nil {
		return x.ClaimerWallet
	}
	return ""
}

func (x *ClaimResultReq) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ClaimResultReq) GetAuthNonce() string {
	if x != nil {
		return x.AuthNonce
	}
	return ""
}

type ClaimResultResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimResultResp) Reset() {
	*x = ClaimResultResp{}
	mi := &file_redpacket_redpacket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimResultResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimResultResp) ProtoMessage() {}

func (x *ClaimResultResp) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimResultResp.ProtoReflect.Descriptor instead.
func (*ClaimResultResp) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{11}
}

func (x *ClaimResultResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type TxResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxResp) Reset() {
	*x = TxResp{}
	mi := &file_redpacket_redpacket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxResp) ProtoMessage() {}

func (x *TxResp) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxResp.ProtoReflect.Descriptor instead.
func (*TxResp) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{12}
}

func (x *TxResp) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type SetSignerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSigner     string                 `protobuf:"bytes,1,opt,name=new_signer,json=newSigner,proto3" json:"new_signer"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSignerReq) Reset() {
	*x = SetSignerReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSignerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSignerReq) ProtoMessage() {}

func (x *SetSignerReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSignerReq.ProtoReflect.Descriptor instead.
func (*SetSignerReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{13}
}

func (x *SetSignerReq) GetNewSigner() string {
	if x != nil {
		return x.NewSigner
	}
	return ""
}

func (x *SetSignerReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type SetTokenReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	Allowed        bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed"`
	MinShareAmount string                 `protobuf:"bytes,3,opt,name=min_share_amount,json=minShareAmount,proto3" json:"min_share_amount"`
	Chain          string                 `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetTokenReq) Reset() {
	*x = SetTokenReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTokenReq) ProtoMessage() {}

func (x *SetTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTokenReq.ProtoReflect.Descriptor instead.
func (*SetTokenReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{14}
}

func (x *SetTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SetTokenReq) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *SetTokenReq) GetMinShareAmount() string {
	if x != nil {
		return x.MinShareAmount
	}
	return ""
}

func (x *SetTokenReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type SetExpiryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      string                 `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetExpiryReq) Reset() {
	*x = SetExpiryReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetExpiryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetExpiryReq) ProtoMessage() {}

func (x *SetExpiryReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetExpiryReq.ProtoReflect.Descriptor instead.
func (*SetExpiryReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{15}
}

func (x *SetExpiryReq) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *SetExpiryReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type SetAllowAllTokensReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAllowAllTokensReq) Reset() {
	*x = SetAllowAllTokensReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAllowAllTokensReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllowAllTokensReq) ProtoMessage() {}

func (x *SetAllowAllTokensReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllowAllTokensReq.ProtoReflect.Descriptor instead.
func (*SetAllowAllTokensReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{16}
}

func (x *SetAllowAllTokensReq) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *SetAllowAllTokensReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type SetNativeTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNativeTokenReq) Reset() {
	*x = SetNativeTokenReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNativeTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNativeTokenReq) ProtoMessage() {}

func (x *SetNativeTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNativeTokenReq.ProtoReflect.Descriptor instead.
func (*SetNativeTokenReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{17}
}

func (x *SetNativeTokenReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetNativeTokenReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type ParseTxEventsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTxEventsReq) Reset() {
	*x = ParseTxEventsReq{}
	mi := &file_redpacket_redpacket_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTxEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTxEventsReq) ProtoMessage() {}

func (x *ParseTxEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTxEventsReq.ProtoReflect.Descriptor instead.
func (*ParseTxEventsReq) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{18}
}

func (x *ParseTxEventsReq) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *ParseTxEventsReq) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type TxEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxEvent) Reset() {
	*x = TxEvent{}
	mi := &file_redpacket_redpacket_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxEvent) ProtoMessage() {}

func (x *TxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxEvent.ProtoReflect.Descriptor instead.
func (*TxEvent) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{19}
}

func (x *TxEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TxEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ParseTxEventsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*TxEvent             `protobuf:"bytes,1,rep,name=events,proto3" json:"events"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseTxEventsResp) Reset() {
	*x = ParseTxEventsResp{}
	mi := &file_redpacket_redpacket_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseTxEventsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseTxEventsResp) ProtoMessage() {}

func (x *ParseTxEventsResp) ProtoReflect() protoreflect.Message {
	mi := &file_redpacket_redpacket_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseTxEventsResp.ProtoReflect.Descriptor instead.
func (*ParseTxEventsResp) Descriptor() ([]byte, []int) {
	return file_redpacket_redpacket_proto_rawDescGZIP(), []int{20}
}

func (x *ParseTxEventsResp) GetEvents() []*TxEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_redpacket_redpacket_proto protoreflect.FileDescriptor

const file_redpacket_redpacket_proto_rawDesc = "" +
	"\n" +
	"\x19redpacket/redpacket.proto\x12\x10openim.redpacket\"\x8f\x02\n" +
	"\x0ecreateOrderReq\x12&\n" +
	"\x0fcreator_user_id\x18\x01 \x01(\tR\rcreatorUserId\x12%\n" +
	"\x0ecreator_wallet\x18\x02 \x01(\tR\rcreatorWallet\x12\x1f\n" +
	"\vpacket_type\x18\x03 \x01(\x05R\n" +
	"packetType\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\tR\vtotalAmount\x12!\n" +
	"\ftotal_shares\x18\x06 \x01(\x05R\vtotalShares\x12\x1b\n" +
	"\texpiry_at\x18\a \x01(\x03R\bexpiryAt\x12\x14\n" +
	"\x05chain\x18\b \x01(\tR\x05chain\"(\n" +
	"\x0fcreateOrderResp\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\"a\n" +
	"\x12createdCallbackReq\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\tR\x05bizId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x1b\n" +
	"\tpacket_id\x18\x03 \x01(\tR\bpacketId\"%\n" +
	"\x13createdCallbackResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"+\n" +
	"\fgetDetailReq\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\tR\bpacketId\"\x89\x04\n" +
	"\x0fredPacketRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06biz_id\x18\x02 \x01(\tR\x05bizId\x12\x1b\n" +
	"\tpacket_id\x18\x03 \x01(\tR\bpacketId\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\x03R\achainId\x12)\n" +
	"\x10contract_address\x18\x05 \x01(\tR\x0fcontractAddress\x12&\n" +
	"\x0fcreator_user_id\x18\x06 \x01(\tR\rcreatorUserId\x12%\n" +
	"\x0ecreator_wallet\x18\a \x01(\tR\rcreatorWallet\x12\x1f\n" +
	"\vpacket_type\x18\b \x01(\x05R\n" +
	"packetType\x12\x14\n" +
	"\x05token\x18\t \x01(\tR\x05token\x12!\n" +
	"\ftotal_amount\x18\n" +
	" \x01(\tR\vtotalAmount\x12!\n" +
	"\ftotal_shares\x18\v \x01(\x05R\vtotalShares\x12\x1b\n" +
	"\texpiry_at\x18\f \x01(\x03R\bexpiryAt\x12\x17\n" +
	"\atx_hash\x18\r \x01(\tR\x06txHash\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12\x14\n" +
	"\x05chain\x18\x0f \x01(\tR\x05chain\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\x03R\tupdatedAt\"\xc4\x02\n" +
	"\vclaimRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tpacket_id\x18\x02 \x01(\tR\bpacketId\x12%\n" +
	"\x0eclaimer_wallet\x18\x03 \x01(\tR\rclaimerWallet\x12\x1d\n" +
	"\n" +
	"auth_nonce\x18\x04 \x01(\tR\tauthNonce\x12\"\n" +
	"\rclaim_tx_hash\x18\x05 \x01(\tR\vclaimTxHash\x12%\n" +
	"\x0eclaimed_amount\x18\x06 \x01(\tR\rclaimedAmount\x12!\n" +
	"\fblock_number\x18\a \x01(\x03R\vblockNumber\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\x88\x01\n" +
	"\rgetDetailResp\x12@\n" +
	"\n" +
	"biz_record\x18\x01 \x01(\v2!.openim.redpacket.redPacketRecordR\tbizRecord\x125\n" +
	"\x06claims\x18\x02 \x03(\v2\x1d.openim.redpacket.claimRecordR\x06claims\"\x7f\n" +
	"\fclaimSignReq\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\tR\bpacketId\x12\x18\n" +
	"\aclaimer\x18\x02 \x01(\tR\aclaimer\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vrandom_seed\x18\x04 \x01(\tR\n" +
	"randomSeed\"\x89\x01\n" +
	"\rclaimSignResp\x12\x1d\n" +
	"\n" +
	"auth_nonce\x18\x01 \x01(\tR\tauthNonce\x12\x1a\n" +
	"\bdeadline\x18\x02 \x01(\x03R\bdeadline\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x1f\n" +
	"\vrandom_seed\x18\x04 \x01(\tR\n" +
	"randomSeed\"\x8c\x01\n" +
	"\x0eclaimResultReq\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\tR\bpacketId\x12%\n" +
	"\x0eclaimer_wallet\x18\x02 \x01(\tR\rclaimerWallet\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x1d\n" +
	"\n" +
	"auth_nonce\x18\x04 \x01(\tR\tauthNonce\"!\n" +
	"\x0fclaimResultResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"!\n" +
	"\x06txResp\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\"C\n" +
	"\fsetSignerReq\x12\x1d\n" +
	"\n" +
	"new_signer\x18\x01 \x01(\tR\tnewSigner\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"}\n" +
	"\vsetTokenReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed\x12(\n" +
	"\x10min_share_amount\x18\x03 \x01(\tR\x0eminShareAmount\x12\x14\n" +
	"\x05chain\x18\x04 \x01(\tR\x05chain\"@\n" +
	"\fsetExpiryReq\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\tR\bduration\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"B\n" +
	"\x14setAllowAllTokensReq\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"C\n" +
	"\x11setNativeTokenReq\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\"A\n" +
	"\x10parseTxEventsReq\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\"1\n" +
	"\atxEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"F\n" +
	"\x11parseTxEventsResp\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.openim.redpacket.txEventR\x06events2\x84\a\n" +
	"\tRedPacket\x12R\n" +
	"\vcreateOrder\x12 .openim.redpacket.createOrderReq\x1a!.openim.redpacket.createOrderResp\x12^\n" +
	"\x0fcreatedCallback\x12$.openim.redpacket.createdCallbackReq\x1a%.openim.redpacket.createdCallbackResp\x12L\n" +
	"\tgetDetail\x12\x1e.openim.redpacket.getDetailReq\x1a\x1f.openim.redpacket.getDetailResp\x12L\n" +
	"\tclaimSign\x12\x1e.openim.redpacket.claimSignReq\x1a\x1f.openim.redpacket.claimSignResp\x12R\n" +
	"\vclaimResult\x12 .openim.redpacket.claimResultReq\x1a!.openim.redpacket.claimResultResp\x12E\n" +
	"\tsetSigner\x12\x1e.openim.redpacket.setSignerReq\x1a\x18.openim.redpacket.txResp\x12C\n" +
	"\bsetToken\x12\x1d.openim.redpacket.setTokenReq\x1a\x18.openim.redpacket.txResp\x12E\n" +
	"\tsetExpiry\x12\x1e.openim.redpacket.setExpiryReq\x1a\x18.openim.redpacket.txResp\x12U\n" +
	"\x11setAllowAllTokens\x12&.openim.redpacket.setAllowAllTokensReq\x1a\x18.openim.redpacket.txResp\x12O\n" +
	"\x0esetNativeToken\x12#.openim.redpacket.setNativeTokenReq\x1a\x18.openim.redpacket.txResp\x12X\n" +
	"\rparseTxEvents\x12\".openim.redpacket.parseTxEventsReq\x1a#.openim.redpacket.parseTxEventsRespB)Z'github.com/openimsdk/protocol/redpacketb\x06proto3"

var (
	file_redpacket_redpacket_proto_rawDescOnce sync.Once
	file_redpacket_redpacket_proto_rawDescData []byte
)

func file_redpacket_redpacket_proto_rawDescGZIP() []byte {
	file_redpacket_redpacket_proto_rawDescOnce.Do(func() {
		file_redpacket_redpacket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redpacket_redpacket_proto_rawDesc), len(file_redpacket_redpacket_proto_rawDesc)))
	})
	return file_redpacket_redpacket_proto_rawDescData
}

var file_redpacket_redpacket_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_redpacket_redpacket_proto_goTypes = []any{
	(*CreateOrderReq)(nil),       // 0: openim.redpacket.createOrderReq
	(*CreateOrderResp)(nil),      // 1: openim.redpacket.createOrderResp
	(*CreatedCallbackReq)(nil),   // 2: openim.redpacket.createdCallbackReq
	(*CreatedCallbackResp)(nil),  // 3: openim.redpacket.createdCallbackResp
	(*GetDetailReq)(nil),         // 4: openim.redpacket.getDetailReq
	(*RedPacketRecord)(nil),      // 5: openim.redpacket.redPacketRecord
	(*ClaimRecord)(nil),          // 6: openim.redpacket.claimRecord
	(*GetDetailResp)(nil),        // 7: openim.redpacket.getDetailResp
	(*ClaimSignReq)(nil),         // 8: openim.redpacket.claimSignReq
	(*ClaimSignResp)(nil),        // 9: openim.redpacket.claimSignResp
	(*ClaimResultReq)(nil),       // 10: openim.redpacket.claimResultReq
	(*ClaimResultResp)(nil),      // 11: openim.redpacket.claimResultResp
	(*TxResp)(nil),               // 12: openim.redpacket.txResp
	(*SetSignerReq)(nil),         // 13: openim.redpacket.setSignerReq
	(*SetTokenReq)(nil),          // 14: openim.redpacket.setTokenReq
	(*SetExpiryReq)(nil),         // 15: openim.redpacket.setExpiryReq
	(*SetAllowAllTokensReq)(nil), // 16: openim.redpacket.setAllowAllTokensReq
	(*SetNativeTokenReq)(nil),    // 17: openim.redpacket.setNativeTokenReq
	(*ParseTxEventsReq)(nil),     // 18: openim.redpacket.parseTxEventsReq
	(*TxEvent)(nil),              // 19: openim.redpacket.txEvent
	(*ParseTxEventsResp)(nil),    // 20: openim.redpacket.parseTxEventsResp
}
var file_redpacket_redpacket_proto_depIdxs = []int32{
	5,  // 0: openim.redpacket.getDetailResp.biz_record:type_name -> openim.redpacket.redPacketRecord
	6,  // 1: openim.redpacket.getDetailResp.claims:type_name -> openim.redpacket.claimRecord
	19, // 2: openim.redpacket.parseTxEventsResp.events:type_name -> openim.redpacket.txEvent
	0,  // 3: openim.redpacket.RedPacket.createOrder:input_type -> openim.redpacket.createOrderReq
	2,  // 4: openim.redpacket.RedPacket.createdCallback:input_type -> openim.redpacket.createdCallbackReq
	4,  // 5: openim.redpacket.RedPacket.getDetail:input_type -> openim.redpacket.getDetailReq
	8,  // 6: openim.redpacket.RedPacket.claimSign:input_type -> openim.redpacket.claimSignReq
	10, // 7: openim.redpacket.RedPacket.claimResult:input_type -> openim.redpacket.claimResultReq
	13, // 8: openim.redpacket.RedPacket.setSigner:input_type -> openim.redpacket.setSignerReq
	14, // 9: openim.redpacket.RedPacket.setToken:input_type -> openim.redpacket.setTokenReq
	15, // 10: openim.redpacket.RedPacket.setExpiry:input_type -> openim.redpacket.setExpiryReq
	16, // 11: openim.redpacket.RedPacket.setAllowAllTokens:input_type -> openim.redpacket.setAllowAllTokensReq
	17, // 12: openim.redpacket.RedPacket.setNativeToken:input_type -> openim.redpacket.setNativeTokenReq
	18, // 13: openim.redpacket.RedPacket.parseTxEvents:input_type -> openim.redpacket.parseTxEventsReq
	1,  // 14: openim.redpacket.RedPacket.createOrder:output_type -> openim.redpacket.createOrderResp
	3,  // 15: openim.redpacket.RedPacket.createdCallback:output_type -> openim.redpacket.createdCallbackResp
	7,  // 16: openim.redpacket.RedPacket.getDetail:output_type -> openim.redpacket.getDetailResp
	9,  // 17: openim.redpacket.RedPacket.claimSign:output_type -> openim.redpacket.claimSignResp
	11, // 18: openim.redpacket.RedPacket.claimResult:output_type -> openim.redpacket.claimResultResp
	12, // 19: openim.redpacket.RedPacket.setSigner:output_type -> openim.redpacket.txResp
	12, // 20: openim.redpacket.RedPacket.setToken:output_type -> openim.redpacket.txResp
	12, // 21: openim.redpacket.RedPacket.setExpiry:output_type -> openim.redpacket.txResp
	12, // 22: openim.redpacket.RedPacket.setAllowAllTokens:output_type -> openim.redpacket.txResp
	12, // 23: openim.redpacket.RedPacket.setNativeToken:output_type -> openim.redpacket.txResp
	20, // 24: openim.redpacket.RedPacket.parseTxEvents:output_type -> openim.redpacket.parseTxEventsResp
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_redpacket_redpacket_proto_init() }
func file_redpacket_redpacket_proto_init() {
	if File_redpacket_redpacket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redpacket_redpacket_proto_rawDesc), len(file_redpacket_redpacket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redpacket_redpacket_proto_goTypes,
		DependencyIndexes: file_redpacket_redpacket_proto_depIdxs,
		MessageInfos:      file_redpacket_redpacket_proto_msgTypes,
	}.Build()
	File_redpacket_redpacket_proto = out.File
	file_redpacket_redpacket_proto_goTypes = nil
	file_redpacket_redpacket_proto_depIdxs = nil
}
