// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: crypto/crypto.proto

package crypto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceID       string                 `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID"`
	UserID         string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID"`
	Platform       string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform"`
	DeviceModel    string                 `protobuf:"bytes,4,opt,name=deviceModel,proto3" json:"deviceModel"`
	AppVersion     string                 `protobuf:"bytes,5,opt,name=appVersion,proto3" json:"appVersion"`
	VirgilIdentity string                 `protobuf:"bytes,6,opt,name=virgilIdentity,proto3" json:"virgilIdentity"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status"`
	LastSeenAt     int64                  `protobuf:"varint,8,opt,name=lastSeenAt,proto3" json:"lastSeenAt"`
	CreateTime     int64                  `protobuf:"varint,9,opt,name=createTime,proto3" json:"createTime"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_crypto_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *DeviceInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeviceInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceInfo) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *DeviceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *DeviceInfo) GetVirgilIdentity() string {
	if x != nil {
		return x.VirgilIdentity
	}
	return ""
}

func (x *DeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceInfo) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *DeviceInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type RegisterDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform"`
	DeviceModel   string                 `protobuf:"bytes,4,opt,name=deviceModel,proto3" json:"deviceModel"`
	AppVersion    string                 `protobuf:"bytes,5,opt,name=appVersion,proto3" json:"appVersion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceReq) Reset() {
	*x = RegisterDeviceReq{}
	mi := &file_crypto_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceReq) ProtoMessage() {}

func (x *RegisterDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceReq.ProtoReflect.Descriptor instead.
func (*RegisterDeviceReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDeviceReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RegisterDeviceReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RegisterDeviceReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceReq) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

func (x *RegisterDeviceReq) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type RegisterDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *DeviceInfo            `protobuf:"bytes,1,opt,name=device,proto3" json:"device"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceResp) Reset() {
	*x = RegisterDeviceResp{}
	mi := &file_crypto_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceResp) ProtoMessage() {}

func (x *RegisterDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceResp.ProtoReflect.Descriptor instead.
func (*RegisterDeviceResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterDeviceResp) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesReq) Reset() {
	*x = GetDevicesReq{}
	mi := &file_crypto_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesReq) ProtoMessage() {}

func (x *GetDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesReq.ProtoReflect.Descriptor instead.
func (*GetDevicesReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *GetDevicesReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetDevicesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResp) Reset() {
	*x = GetDevicesResp{}
	mi := &file_crypto_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResp) ProtoMessage() {}

func (x *GetDevicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResp.ProtoReflect.Descriptor instead.
func (*GetDevicesResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{4}
}

func (x *GetDevicesResp) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type RevokeDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceReq) Reset() {
	*x = RevokeDeviceReq{}
	mi := &file_crypto_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceReq) ProtoMessage() {}

func (x *RevokeDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceReq.ProtoReflect.Descriptor instead.
func (*RevokeDeviceReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeDeviceReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RevokeDeviceReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type RevokeDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceResp) Reset() {
	*x = RevokeDeviceResp{}
	mi := &file_crypto_crypto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceResp) ProtoMessage() {}

func (x *RevokeDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceResp.ProtoReflect.Descriptor instead.
func (*RevokeDeviceResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{6}
}

type GetVirgilJWTReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVirgilJWTReq) Reset() {
	*x = GetVirgilJWTReq{}
	mi := &file_crypto_crypto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirgilJWTReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirgilJWTReq) ProtoMessage() {}

func (x *GetVirgilJWTReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirgilJWTReq.ProtoReflect.Descriptor instead.
func (*GetVirgilJWTReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{7}
}

func (x *GetVirgilJWTReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetVirgilJWTReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type GetVirgilJWTResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VirgilJWT      string                 `protobuf:"bytes,1,opt,name=virgilJWT,proto3" json:"virgilJWT"`
	ExpiresIn      int64                  `protobuf:"varint,2,opt,name=expiresIn,proto3" json:"expiresIn"`
	VirgilIdentity string                 `protobuf:"bytes,3,opt,name=virgilIdentity,proto3" json:"virgilIdentity"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVirgilJWTResp) Reset() {
	*x = GetVirgilJWTResp{}
	mi := &file_crypto_crypto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVirgilJWTResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVirgilJWTResp) ProtoMessage() {}

func (x *GetVirgilJWTResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVirgilJWTResp.ProtoReflect.Descriptor instead.
func (*GetVirgilJWTResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{8}
}

func (x *GetVirgilJWTResp) GetVirgilJWT() string {
	if x != nil {
		return x.VirgilJWT
	}
	return ""
}

func (x *GetVirgilJWTResp) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *GetVirgilJWTResp) GetVirgilIdentity() string {
	if x != nil {
		return x.VirgilIdentity
	}
	return ""
}

type GroupKeyVersionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupID         string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	GroupKeyVersion int64                  `protobuf:"varint,2,opt,name=groupKeyVersion,proto3" json:"groupKeyVersion"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupKeyVersionInfo) Reset() {
	*x = GroupKeyVersionInfo{}
	mi := &file_crypto_crypto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupKeyVersionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupKeyVersionInfo) ProtoMessage() {}

func (x *GroupKeyVersionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupKeyVersionInfo.ProtoReflect.Descriptor instead.
func (*GroupKeyVersionInfo) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{9}
}

func (x *GroupKeyVersionInfo) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GroupKeyVersionInfo) GetGroupKeyVersion() int64 {
	if x != nil {
		return x.GroupKeyVersion
	}
	return 0
}

type GetGroupKeyVersionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupKeyVersionReq) Reset() {
	*x = GetGroupKeyVersionReq{}
	mi := &file_crypto_crypto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupKeyVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupKeyVersionReq) ProtoMessage() {}

func (x *GetGroupKeyVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupKeyVersionReq.ProtoReflect.Descriptor instead.
func (*GetGroupKeyVersionReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{10}
}

func (x *GetGroupKeyVersionReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

type GetGroupKeyVersionResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupID         string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	GroupKeyVersion int64                  `protobuf:"varint,2,opt,name=groupKeyVersion,proto3" json:"groupKeyVersion"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetGroupKeyVersionResp) Reset() {
	*x = GetGroupKeyVersionResp{}
	mi := &file_crypto_crypto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupKeyVersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupKeyVersionResp) ProtoMessage() {}

func (x *GetGroupKeyVersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupKeyVersionResp.ProtoReflect.Descriptor instead.
func (*GetGroupKeyVersionResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{11}
}

func (x *GetGroupKeyVersionResp) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GetGroupKeyVersionResp) GetGroupKeyVersion() int64 {
	if x != nil {
		return x.GroupKeyVersion
	}
	return 0
}

type BumpGroupKeyVersionReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupID        string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	OperatorUserID string                 `protobuf:"bytes,2,opt,name=operatorUserID,proto3" json:"operatorUserID"`
	EventType      string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BumpGroupKeyVersionReq) Reset() {
	*x = BumpGroupKeyVersionReq{}
	mi := &file_crypto_crypto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BumpGroupKeyVersionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpGroupKeyVersionReq) ProtoMessage() {}

func (x *BumpGroupKeyVersionReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpGroupKeyVersionReq.ProtoReflect.Descriptor instead.
func (*BumpGroupKeyVersionReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{12}
}

func (x *BumpGroupKeyVersionReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *BumpGroupKeyVersionReq) GetOperatorUserID() string {
	if x != nil {
		return x.OperatorUserID
	}
	return ""
}

func (x *BumpGroupKeyVersionReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type BumpGroupKeyVersionResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupID         string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	GroupKeyVersion int64                  `protobuf:"varint,2,opt,name=groupKeyVersion,proto3" json:"groupKeyVersion"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BumpGroupKeyVersionResp) Reset() {
	*x = BumpGroupKeyVersionResp{}
	mi := &file_crypto_crypto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BumpGroupKeyVersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BumpGroupKeyVersionResp) ProtoMessage() {}

func (x *BumpGroupKeyVersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BumpGroupKeyVersionResp.ProtoReflect.Descriptor instead.
func (*BumpGroupKeyVersionResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{13}
}

func (x *BumpGroupKeyVersionResp) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *BumpGroupKeyVersionResp) GetGroupKeyVersion() int64 {
	if x != nil {
		return x.GroupKeyVersion
	}
	return 0
}

type GroupKeyEventInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventID         string                 `protobuf:"bytes,1,opt,name=eventID,proto3" json:"eventID"`
	GroupID         string                 `protobuf:"bytes,2,opt,name=groupID,proto3" json:"groupID"`
	GroupKeyVersion int64                  `protobuf:"varint,3,opt,name=groupKeyVersion,proto3" json:"groupKeyVersion"`
	EventType       string                 `protobuf:"bytes,4,opt,name=eventType,proto3" json:"eventType"`
	OperatorUserID  string                 `protobuf:"bytes,5,opt,name=operatorUserID,proto3" json:"operatorUserID"`
	CreateTime      int64                  `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupKeyEventInfo) Reset() {
	*x = GroupKeyEventInfo{}
	mi := &file_crypto_crypto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupKeyEventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupKeyEventInfo) ProtoMessage() {}

func (x *GroupKeyEventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupKeyEventInfo.ProtoReflect.Descriptor instead.
func (*GroupKeyEventInfo) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{14}
}

func (x *GroupKeyEventInfo) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *GroupKeyEventInfo) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GroupKeyEventInfo) GetGroupKeyVersion() int64 {
	if x != nil {
		return x.GroupKeyVersion
	}
	return 0
}

func (x *GroupKeyEventInfo) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GroupKeyEventInfo) GetOperatorUserID() string {
	if x != nil {
		return x.OperatorUserID
	}
	return ""
}

func (x *GroupKeyEventInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type GetGroupKeyEventsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	SinceVersion  int64                  `protobuf:"varint,2,opt,name=sinceVersion,proto3" json:"sinceVersion"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupKeyEventsReq) Reset() {
	*x = GetGroupKeyEventsReq{}
	mi := &file_crypto_crypto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupKeyEventsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupKeyEventsReq) ProtoMessage() {}

func (x *GetGroupKeyEventsReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupKeyEventsReq.ProtoReflect.Descriptor instead.
func (*GetGroupKeyEventsReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{15}
}

func (x *GetGroupKeyEventsReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *GetGroupKeyEventsReq) GetSinceVersion() int64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

type GetGroupKeyEventsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*GroupKeyEventInfo   `protobuf:"bytes,1,rep,name=events,proto3" json:"events"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupKeyEventsResp) Reset() {
	*x = GetGroupKeyEventsResp{}
	mi := &file_crypto_crypto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupKeyEventsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupKeyEventsResp) ProtoMessage() {}

func (x *GetGroupKeyEventsResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupKeyEventsResp.ProtoReflect.Descriptor instead.
func (*GetGroupKeyEventsResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{16}
}

func (x *GetGroupKeyEventsResp) GetEvents() []*GroupKeyEventInfo {
	if x != nil {
		return x.Events
	}
	return nil
}

type SecurityPrecheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityPrecheckReq) Reset() {
	*x = SecurityPrecheckReq{}
	mi := &file_crypto_crypto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityPrecheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityPrecheckReq) ProtoMessage() {}

func (x *SecurityPrecheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityPrecheckReq.ProtoReflect.Descriptor instead.
func (*SecurityPrecheckReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{17}
}

func (x *SecurityPrecheckReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SecurityPrecheckReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *SecurityPrecheckReq) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type SecurityPrecheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityPrecheckResp) Reset() {
	*x = SecurityPrecheckResp{}
	mi := &file_crypto_crypto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityPrecheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityPrecheckResp) ProtoMessage() {}

func (x *SecurityPrecheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityPrecheckResp.ProtoReflect.Descriptor instead.
func (*SecurityPrecheckResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{18}
}

func (x *SecurityPrecheckResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *SecurityPrecheckResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type IntegrityReportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID"`
	ReportData    string                 `protobuf:"bytes,3,opt,name=reportData,proto3" json:"reportData"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrityReportReq) Reset() {
	*x = IntegrityReportReq{}
	mi := &file_crypto_crypto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityReportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityReportReq) ProtoMessage() {}

func (x *IntegrityReportReq) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityReportReq.ProtoReflect.Descriptor instead.
func (*IntegrityReportReq) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{19}
}

func (x *IntegrityReportReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *IntegrityReportReq) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *IntegrityReportReq) GetReportData() string {
	if x != nil {
		return x.ReportData
	}
	return ""
}

func (x *IntegrityReportReq) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IntegrityReportResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrityReportResp) Reset() {
	*x = IntegrityReportResp{}
	mi := &file_crypto_crypto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityReportResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityReportResp) ProtoMessage() {}

func (x *IntegrityReportResp) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_crypto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityReportResp.ProtoReflect.Descriptor instead.
func (*IntegrityReportResp) Descriptor() ([]byte, []int) {
	return file_crypto_crypto_proto_rawDescGZIP(), []int{20}
}

func (x *IntegrityReportResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_crypto_crypto_proto protoreflect.FileDescriptor

const file_crypto_crypto_proto_rawDesc = "" +
	"\n" +
	"\x13crypto/crypto.proto\x12\ropenim.crypto\"\x9e\x02\n" +
	"\n" +
	"DeviceInfo\x12\x1a\n" +
	"\bdeviceID\x18\x01 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12 \n" +
	"\vdeviceModel\x18\x04 \x01(\tR\vdeviceModel\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x05 \x01(\tR\n" +
	"appVersion\x12&\n" +
	"\x0evirgilIdentity\x18\x06 \x01(\tR\x0evirgilIdentity\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"lastSeenAt\x18\b \x01(\x03R\n" +
	"lastSeenAt\x12\x1e\n" +
	"\n" +
	"createTime\x18\t \x01(\x03R\n" +
	"createTime\"\xa5\x01\n" +
	"\x11RegisterDeviceReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12 \n" +
	"\vdeviceModel\x18\x04 \x01(\tR\vdeviceModel\x12\x1e\n" +
	"\n" +
	"appVersion\x18\x05 \x01(\tR\n" +
	"appVersion\"G\n" +
	"\x12RegisterDeviceResp\x121\n" +
	"\x06device\x18\x01 \x01(\v2\x19.openim.crypto.DeviceInfoR\x06device\"'\n" +
	"\rGetDevicesReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\"E\n" +
	"\x0eGetDevicesResp\x123\n" +
	"\adevices\x18\x01 \x03(\v2\x19.openim.crypto.DeviceInfoR\adevices\"E\n" +
	"\x0fRevokeDeviceReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\"\x12\n" +
	"\x10RevokeDeviceResp\"E\n" +
	"\x0fGetVirgilJWTReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\"v\n" +
	"\x10GetVirgilJWTResp\x12\x1c\n" +
	"\tvirgilJWT\x18\x01 \x01(\tR\tvirgilJWT\x12\x1c\n" +
	"\texpiresIn\x18\x02 \x01(\x03R\texpiresIn\x12&\n" +
	"\x0evirgilIdentity\x18\x03 \x01(\tR\x0evirgilIdentity\"Y\n" +
	"\x13GroupKeyVersionInfo\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12(\n" +
	"\x0fgroupKeyVersion\x18\x02 \x01(\x03R\x0fgroupKeyVersion\"1\n" +
	"\x15GetGroupKeyVersionReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\"\\\n" +
	"\x16GetGroupKeyVersionResp\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12(\n" +
	"\x0fgroupKeyVersion\x18\x02 \x01(\x03R\x0fgroupKeyVersion\"x\n" +
	"\x16BumpGroupKeyVersionReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12&\n" +
	"\x0eoperatorUserID\x18\x02 \x01(\tR\x0eoperatorUserID\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\"]\n" +
	"\x17BumpGroupKeyVersionResp\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12(\n" +
	"\x0fgroupKeyVersion\x18\x02 \x01(\x03R\x0fgroupKeyVersion\"\xd7\x01\n" +
	"\x11GroupKeyEventInfo\x12\x18\n" +
	"\aeventID\x18\x01 \x01(\tR\aeventID\x12\x18\n" +
	"\agroupID\x18\x02 \x01(\tR\agroupID\x12(\n" +
	"\x0fgroupKeyVersion\x18\x03 \x01(\x03R\x0fgroupKeyVersion\x12\x1c\n" +
	"\teventType\x18\x04 \x01(\tR\teventType\x12&\n" +
	"\x0eoperatorUserID\x18\x05 \x01(\tR\x0eoperatorUserID\x12\x1e\n" +
	"\n" +
	"createTime\x18\x06 \x01(\x03R\n" +
	"createTime\"T\n" +
	"\x14GetGroupKeyEventsReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12\"\n" +
	"\fsinceVersion\x18\x02 \x01(\x03R\fsinceVersion\"Q\n" +
	"\x15GetGroupKeyEventsResp\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .openim.crypto.GroupKeyEventInfoR\x06events\"a\n" +
	"\x13SecurityPrecheckReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"H\n" +
	"\x14SecurityPrecheckResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x86\x01\n" +
	"\x12IntegrityReportReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x12\x1e\n" +
	"\n" +
	"reportData\x18\x03 \x01(\tR\n" +
	"reportData\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"1\n" +
	"\x13IntegrityReportResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xb3\x06\n" +
	"\rCryptoService\x12U\n" +
	"\x0eRegisterDevice\x12 .openim.crypto.RegisterDeviceReq\x1a!.openim.crypto.RegisterDeviceResp\x12I\n" +
	"\n" +
	"GetDevices\x12\x1c.openim.crypto.GetDevicesReq\x1a\x1d.openim.crypto.GetDevicesResp\x12O\n" +
	"\fRevokeDevice\x12\x1e.openim.crypto.RevokeDeviceReq\x1a\x1f.openim.crypto.RevokeDeviceResp\x12O\n" +
	"\fGetVirgilJWT\x12\x1e.openim.crypto.GetVirgilJWTReq\x1a\x1f.openim.crypto.GetVirgilJWTResp\x12a\n" +
	"\x12GetGroupKeyVersion\x12$.openim.crypto.GetGroupKeyVersionReq\x1a%.openim.crypto.GetGroupKeyVersionResp\x12d\n" +
	"\x13BumpGroupKeyVersion\x12%.openim.crypto.BumpGroupKeyVersionReq\x1a&.openim.crypto.BumpGroupKeyVersionResp\x12^\n" +
	"\x11GetGroupKeyEvents\x12#.openim.crypto.GetGroupKeyEventsReq\x1a$.openim.crypto.GetGroupKeyEventsResp\x12[\n" +
	"\x10SecurityPrecheck\x12\".openim.crypto.SecurityPrecheckReq\x1a#.openim.crypto.SecurityPrecheckResp\x12X\n" +
	"\x0fIntegrityReport\x12!.openim.crypto.IntegrityReportReq\x1a\".openim.crypto.IntegrityReportRespB&Z$github.com/openimsdk/protocol/cryptob\x06proto3"

var (
	file_crypto_crypto_proto_rawDescOnce sync.Once
	file_crypto_crypto_proto_rawDescData []byte
)

func file_crypto_crypto_proto_rawDescGZIP() []byte {
	file_crypto_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_crypto_proto_rawDesc), len(file_crypto_crypto_proto_rawDesc)))
	})
	return file_crypto_crypto_proto_rawDescData
}

var file_crypto_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_crypto_crypto_proto_goTypes = []any{
	(*DeviceInfo)(nil),              // 0: openim.crypto.DeviceInfo
	(*RegisterDeviceReq)(nil),       // 1: openim.crypto.RegisterDeviceReq
	(*RegisterDeviceResp)(nil),      // 2: openim.crypto.RegisterDeviceResp
	(*GetDevicesReq)(nil),           // 3: openim.crypto.GetDevicesReq
	(*GetDevicesResp)(nil),          // 4: openim.crypto.GetDevicesResp
	(*RevokeDeviceReq)(nil),         // 5: openim.crypto.RevokeDeviceReq
	(*RevokeDeviceResp)(nil),        // 6: openim.crypto.RevokeDeviceResp
	(*GetVirgilJWTReq)(nil),         // 7: openim.crypto.GetVirgilJWTReq
	(*GetVirgilJWTResp)(nil),        // 8: openim.crypto.GetVirgilJWTResp
	(*GroupKeyVersionInfo)(nil),     // 9: openim.crypto.GroupKeyVersionInfo
	(*GetGroupKeyVersionReq)(nil),   // 10: openim.crypto.GetGroupKeyVersionReq
	(*GetGroupKeyVersionResp)(nil),  // 11: openim.crypto.GetGroupKeyVersionResp
	(*BumpGroupKeyVersionReq)(nil),  // 12: openim.crypto.BumpGroupKeyVersionReq
	(*BumpGroupKeyVersionResp)(nil), // 13: openim.crypto.BumpGroupKeyVersionResp
	(*GroupKeyEventInfo)(nil),       // 14: openim.crypto.GroupKeyEventInfo
	(*GetGroupKeyEventsReq)(nil),    // 15: openim.crypto.GetGroupKeyEventsReq
	(*GetGroupKeyEventsResp)(nil),   // 16: openim.crypto.GetGroupKeyEventsResp
	(*SecurityPrecheckReq)(nil),     // 17: openim.crypto.SecurityPrecheckReq
	(*SecurityPrecheckResp)(nil),    // 18: openim.crypto.SecurityPrecheckResp
	(*IntegrityReportReq)(nil),      // 19: openim.crypto.IntegrityReportReq
	(*IntegrityReportResp)(nil),     // 20: openim.crypto.IntegrityReportResp
}
var file_crypto_crypto_proto_depIdxs = []int32{
	0,  // 0: openim.crypto.RegisterDeviceResp.device:type_name -> openim.crypto.DeviceInfo
	0,  // 1: openim.crypto.GetDevicesResp.devices:type_name -> openim.crypto.DeviceInfo
	14, // 2: openim.crypto.GetGroupKeyEventsResp.events:type_name -> openim.crypto.GroupKeyEventInfo
	1,  // 3: openim.crypto.CryptoService.RegisterDevice:input_type -> openim.crypto.RegisterDeviceReq
	3,  // 4: openim.crypto.CryptoService.GetDevices:input_type -> openim.crypto.GetDevicesReq
	5,  // 5: openim.crypto.CryptoService.RevokeDevice:input_type -> openim.crypto.RevokeDeviceReq
	7,  // 6: openim.crypto.CryptoService.GetVirgilJWT:input_type -> openim.crypto.GetVirgilJWTReq
	10, // 7: openim.crypto.CryptoService.GetGroupKeyVersion:input_type -> openim.crypto.GetGroupKeyVersionReq
	12, // 8: openim.crypto.CryptoService.BumpGroupKeyVersion:input_type -> openim.crypto.BumpGroupKeyVersionReq
	15, // 9: openim.crypto.CryptoService.GetGroupKeyEvents:input_type -> openim.crypto.GetGroupKeyEventsReq
	17, // 10: openim.crypto.CryptoService.SecurityPrecheck:input_type -> openim.crypto.SecurityPrecheckReq
	19, // 11: openim.crypto.CryptoService.IntegrityReport:input_type -> openim.crypto.IntegrityReportReq
	2,  // 12: openim.crypto.CryptoService.RegisterDevice:output_type -> openim.crypto.RegisterDeviceResp
	4,  // 13: openim.crypto.CryptoService.GetDevices:output_type -> openim.crypto.GetDevicesResp
	6,  // 14: openim.crypto.CryptoService.RevokeDevice:output_type -> openim.crypto.RevokeDeviceResp
	8,  // 15: openim.crypto.CryptoService.GetVirgilJWT:output_type -> openim.crypto.GetVirgilJWTResp
	11, // 16: openim.crypto.CryptoService.GetGroupKeyVersion:output_type -> openim.crypto.GetGroupKeyVersionResp
	13, // 17: openim.crypto.CryptoService.BumpGroupKeyVersion:output_type -> openim.crypto.BumpGroupKeyVersionResp
	16, // 18: openim.crypto.CryptoService.GetGroupKeyEvents:output_type -> openim.crypto.GetGroupKeyEventsResp
	18, // 19: openim.crypto.CryptoService.SecurityPrecheck:output_type -> openim.crypto.SecurityPrecheckResp
	20, // 20: openim.crypto.CryptoService.IntegrityReport:output_type -> openim.crypto.IntegrityReportResp
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_crypto_crypto_proto_init() }
func file_crypto_crypto_proto_init() {
	if File_crypto_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_crypto_proto_rawDesc), len(file_crypto_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_crypto_proto_msgTypes,
	}.Build()
	File_crypto_crypto_proto = out.File
	file_crypto_crypto_proto_goTypes = nil
	file_crypto_crypto_proto_depIdxs = nil
}
