// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.0
// source: crypto/crypto.proto

package crypto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoService_RegisterDevice_FullMethodName      = "/openim.crypto.CryptoService/RegisterDevice"
	CryptoService_GetDevices_FullMethodName          = "/openim.crypto.CryptoService/GetDevices"
	CryptoService_RevokeDevice_FullMethodName        = "/openim.crypto.CryptoService/RevokeDevice"
	CryptoService_GetVirgilJWT_FullMethodName        = "/openim.crypto.CryptoService/GetVirgilJWT"
	CryptoService_GetGroupKeyVersion_FullMethodName  = "/openim.crypto.CryptoService/GetGroupKeyVersion"
	CryptoService_BumpGroupKeyVersion_FullMethodName = "/openim.crypto.CryptoService/BumpGroupKeyVersion"
	CryptoService_GetGroupKeyEvents_FullMethodName   = "/openim.crypto.CryptoService/GetGroupKeyEvents"
	CryptoService_SecurityPrecheck_FullMethodName    = "/openim.crypto.CryptoService/SecurityPrecheck"
	CryptoService_IntegrityReport_FullMethodName     = "/openim.crypto.CryptoService/IntegrityReport"
)

// CryptoServiceClient is the client API for CryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoServiceClient interface {
	// Device management
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error)
	GetDevices(ctx context.Context, in *GetDevicesReq, opts ...grpc.CallOption) (*GetDevicesResp, error)
	RevokeDevice(ctx context.Context, in *RevokeDeviceReq, opts ...grpc.CallOption) (*RevokeDeviceResp, error)
	// Virgil JWT
	GetVirgilJWT(ctx context.Context, in *GetVirgilJWTReq, opts ...grpc.CallOption) (*GetVirgilJWTResp, error)
	// Group key version
	GetGroupKeyVersion(ctx context.Context, in *GetGroupKeyVersionReq, opts ...grpc.CallOption) (*GetGroupKeyVersionResp, error)
	BumpGroupKeyVersion(ctx context.Context, in *BumpGroupKeyVersionReq, opts ...grpc.CallOption) (*BumpGroupKeyVersionResp, error)
	GetGroupKeyEvents(ctx context.Context, in *GetGroupKeyEventsReq, opts ...grpc.CallOption) (*GetGroupKeyEventsResp, error)
	// Security
	SecurityPrecheck(ctx context.Context, in *SecurityPrecheckReq, opts ...grpc.CallOption) (*SecurityPrecheckResp, error)
	IntegrityReport(ctx context.Context, in *IntegrityReportReq, opts ...grpc.CallOption) (*IntegrityReportResp, error)
}

type cryptoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoServiceClient(cc grpc.ClientConnInterface) CryptoServiceClient {
	return &cryptoServiceClient{cc}
}

func (c *cryptoServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResp)
	err := c.cc.Invoke(ctx, CryptoService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) GetDevices(ctx context.Context, in *GetDevicesReq, opts ...grpc.CallOption) (*GetDevicesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDevicesResp)
	err := c.cc.Invoke(ctx, CryptoService_GetDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceReq, opts ...grpc.CallOption) (*RevokeDeviceResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDeviceResp)
	err := c.cc.Invoke(ctx, CryptoService_RevokeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) GetVirgilJWT(ctx context.Context, in *GetVirgilJWTReq, opts ...grpc.CallOption) (*GetVirgilJWTResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVirgilJWTResp)
	err := c.cc.Invoke(ctx, CryptoService_GetVirgilJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) GetGroupKeyVersion(ctx context.Context, in *GetGroupKeyVersionReq, opts ...grpc.CallOption) (*GetGroupKeyVersionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupKeyVersionResp)
	err := c.cc.Invoke(ctx, CryptoService_GetGroupKeyVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) BumpGroupKeyVersion(ctx context.Context, in *BumpGroupKeyVersionReq, opts ...grpc.CallOption) (*BumpGroupKeyVersionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BumpGroupKeyVersionResp)
	err := c.cc.Invoke(ctx, CryptoService_BumpGroupKeyVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) GetGroupKeyEvents(ctx context.Context, in *GetGroupKeyEventsReq, opts ...grpc.CallOption) (*GetGroupKeyEventsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupKeyEventsResp)
	err := c.cc.Invoke(ctx, CryptoService_GetGroupKeyEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) SecurityPrecheck(ctx context.Context, in *SecurityPrecheckReq, opts ...grpc.CallOption) (*SecurityPrecheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityPrecheckResp)
	err := c.cc.Invoke(ctx, CryptoService_SecurityPrecheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) IntegrityReport(ctx context.Context, in *IntegrityReportReq, opts ...grpc.CallOption) (*IntegrityReportResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntegrityReportResp)
	err := c.cc.Invoke(ctx, CryptoService_IntegrityReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoServiceServer is the server API for CryptoService service.
// All implementations must embed UnimplementedCryptoServiceServer
// for forward compatibility.
type CryptoServiceServer interface {
	// Device management
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error)
	GetDevices(context.Context, *GetDevicesReq) (*GetDevicesResp, error)
	RevokeDevice(context.Context, *RevokeDeviceReq) (*RevokeDeviceResp, error)
	// Virgil JWT
	GetVirgilJWT(context.Context, *GetVirgilJWTReq) (*GetVirgilJWTResp, error)
	// Group key version
	GetGroupKeyVersion(context.Context, *GetGroupKeyVersionReq) (*GetGroupKeyVersionResp, error)
	BumpGroupKeyVersion(context.Context, *BumpGroupKeyVersionReq) (*BumpGroupKeyVersionResp, error)
	GetGroupKeyEvents(context.Context, *GetGroupKeyEventsReq) (*GetGroupKeyEventsResp, error)
	// Security
	SecurityPrecheck(context.Context, *SecurityPrecheckReq) (*SecurityPrecheckResp, error)
	IntegrityReport(context.Context, *IntegrityReportReq) (*IntegrityReportResp, error)
	mustEmbedUnimplementedCryptoServiceServer()
}

// UnimplementedCryptoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoServiceServer struct{}

func (UnimplementedCryptoServiceServer) RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedCryptoServiceServer) GetDevices(context.Context, *GetDevicesReq) (*GetDevicesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevices not implemented")
}
func (UnimplementedCryptoServiceServer) RevokeDevice(context.Context, *RevokeDeviceReq) (*RevokeDeviceResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedCryptoServiceServer) GetVirgilJWT(context.Context, *GetVirgilJWTReq) (*GetVirgilJWTResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVirgilJWT not implemented")
}
func (UnimplementedCryptoServiceServer) GetGroupKeyVersion(context.Context, *GetGroupKeyVersionReq) (*GetGroupKeyVersionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupKeyVersion not implemented")
}
func (UnimplementedCryptoServiceServer) BumpGroupKeyVersion(context.Context, *BumpGroupKeyVersionReq) (*BumpGroupKeyVersionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BumpGroupKeyVersion not implemented")
}
func (UnimplementedCryptoServiceServer) GetGroupKeyEvents(context.Context, *GetGroupKeyEventsReq) (*GetGroupKeyEventsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupKeyEvents not implemented")
}
func (UnimplementedCryptoServiceServer) SecurityPrecheck(context.Context, *SecurityPrecheckReq) (*SecurityPrecheckResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SecurityPrecheck not implemented")
}
func (UnimplementedCryptoServiceServer) IntegrityReport(context.Context, *IntegrityReportReq) (*IntegrityReportResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IntegrityReport not implemented")
}
func (UnimplementedCryptoServiceServer) mustEmbedUnimplementedCryptoServiceServer() {}
func (UnimplementedCryptoServiceServer) testEmbeddedByValue()                       {}

// UnsafeCryptoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoServiceServer will
// result in compilation errors.
type UnsafeCryptoServiceServer interface {
	mustEmbedUnimplementedCryptoServiceServer()
}

func RegisterCryptoServiceServer(s grpc.ServiceRegistrar, srv CryptoServiceServer) {
	// If the following call panics, it indicates UnimplementedCryptoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoService_ServiceDesc, srv)
}

func _CryptoService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_GetDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).GetDevices(ctx, req.(*GetDevicesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_GetVirgilJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVirgilJWTReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).GetVirgilJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_GetVirgilJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).GetVirgilJWT(ctx, req.(*GetVirgilJWTReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_GetGroupKeyVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupKeyVersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).GetGroupKeyVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_GetGroupKeyVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).GetGroupKeyVersion(ctx, req.(*GetGroupKeyVersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_BumpGroupKeyVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BumpGroupKeyVersionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).BumpGroupKeyVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_BumpGroupKeyVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).BumpGroupKeyVersion(ctx, req.(*BumpGroupKeyVersionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_GetGroupKeyEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupKeyEventsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).GetGroupKeyEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_GetGroupKeyEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).GetGroupKeyEvents(ctx, req.(*GetGroupKeyEventsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_SecurityPrecheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityPrecheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).SecurityPrecheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_SecurityPrecheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).SecurityPrecheck(ctx, req.(*SecurityPrecheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_IntegrityReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrityReportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).IntegrityReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_IntegrityReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).IntegrityReport(ctx, req.(*IntegrityReportReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoService_ServiceDesc is the grpc.ServiceDesc for CryptoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openim.crypto.CryptoService",
	HandlerType: (*CryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _CryptoService_RegisterDevice_Handler,
		},
		{
			MethodName: "GetDevices",
			Handler:    _CryptoService_GetDevices_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _CryptoService_RevokeDevice_Handler,
		},
		{
			MethodName: "GetVirgilJWT",
			Handler:    _CryptoService_GetVirgilJWT_Handler,
		},
		{
			MethodName: "GetGroupKeyVersion",
			Handler:    _CryptoService_GetGroupKeyVersion_Handler,
		},
		{
			MethodName: "BumpGroupKeyVersion",
			Handler:    _CryptoService_BumpGroupKeyVersion_Handler,
		},
		{
			MethodName: "GetGroupKeyEvents",
			Handler:    _CryptoService_GetGroupKeyEvents_Handler,
		},
		{
			MethodName: "SecurityPrecheck",
			Handler:    _CryptoService_SecurityPrecheck_Handler,
		},
		{
			MethodName: "IntegrityReport",
			Handler:    _CryptoService_IntegrityReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crypto/crypto.proto",
}
